https://github.com/canonical/cloud-init/commit/6b5c306b537aafeded249fc82a3317fba8214508

=== Begin SRU Template ===
[Impact]

cloud-init, previously, could not consume vendor-data from NoCloud seeds, a
divergence in behaviour from most other data sources.

[Test Case]

There is an upstream integration test for this bug:
https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/bugs/test_gh570.py

xenial:

```
GLOB sdist-make: /home/daniel/dev/cloud-init/setup.py
xenial inst-nodeps: /tmp/integration-tests-tox/.tmp/package/1/cloud-init-20.4.zip
xenial installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/1/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@324763289c9a38fc9ac7ec524acb9eb11c7d6c13,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==20.0.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
xenial run-test-pre: PYTHONHASHSEED='1148025086'
xenial run-test: commands[0] | /tmp/integration-tests-tox/xenial/bin/python -m pytest --log-cli-level=INFO bugs/test_gh570.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/xenial/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item

bugs/test_gh570.py::test_nocloud_seedfrom_vendordata
------------------------------------------ live log setup ------------------------------------------
2020-12-10 21:06:10 INFO      integration_testing:clouds.py:73 Detected image: image_id=xenial os=ubuntu release=xenial
2020-12-10 21:06:10 INFO      integration_testing:clouds.py:73 Detected image: image_id=xenial os=ubuntu release=xenial
2020-12-10 21:06:21 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=xenial
PLATFORM=lxd_container
RUN_UNSTABLE=False
2020-12-10 21:06:21 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_container
2020-12-10 21:06:21 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:0f411e79e10761ad7aa433a4965fbc2fef18a47879a9c4ff0408884d41e2bb54
user_data=None
wait=False
2020-12-10 21:06:25 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:06:26 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:06:36 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:06:46 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:06:47 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:07:00 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=eminent-terrier)
2020-12-10 21:07:00 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-10 21:07:00 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-10 21:07:15 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-10 21:07:15 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~16.04.1
2020-12-10 21:07:15 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:16 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:07:16 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:17 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:07:17 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:17 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:08:04 INFO      integration_testing:instances.py:117 Created new image: local:eminent-terrier-snapshot
2020-12-10 21:08:05 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-10 21:08:05 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:eminent-terrier-snapshot
user_data=None
wait=False
2020-12-10 21:08:15 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:08:15 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:08:15 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:08:25 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=advanced-crane)
------------------------------------------ live log call -------------------------------------------
2020-12-10 21:08:25 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'mkdir /var/tmp/test_seed_dir && touch /var/tmp/test_seed_dir/user-data && touch /var/tmp/test_seed_dir/meta-data && echo '"'"'seedfrom: /var/tmp/test_seed_dir/'"'"' > /var/lib/cloud/seed/nocloud-net/meta-data'
2020-12-10 21:08:25 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'mv /var/tmp/f746b41f-1b6d-4a6e-8b85-827739d7bd2a.tmp /var/tmp/test_seed_dir/vendor-data'
2020-12-10 21:08:25 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init clean --logs'
2020-12-10 21:08:29 INFO      integration_testing:instances.py:67 Instance restarted; waiting for boot
2020-12-10 21:08:29 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:08:29 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:08:29 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:08:32 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ls /var/tmp'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-10 21:08:34 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:eminent-terrier-snapshot


========================================= warnings summary =========================================
tests/integration_tests/bugs/test_gh570.py::test_nocloud_seedfrom_vendordata
  /tmp/integration-tests-tox/xenial/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= 1 passed, 1 warning in 144.14s (0:02:24) =============================
```

bionic:

```
GLOB sdist-make: /home/daniel/dev/cloud-init/setup.py
bionic inst-nodeps: /tmp/integration-tests-tox/.tmp/package/2/cloud-init-20.4.zip
bionic installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/2/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@324763289c9a38fc9ac7ec524acb9eb11c7d6c13,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==19.1.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
bionic run-test-pre: PYTHONHASHSEED='1241849639'
bionic run-test: commands[0] | /tmp/integration-tests-tox/bionic/bin/python -m pytest --log-cli-level=INFO bugs/test_gh570.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/bionic/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item

bugs/test_gh570.py::test_nocloud_seedfrom_vendordata
------------------------------------------ live log setup ------------------------------------------
2020-12-10 21:06:15 INFO      integration_testing:clouds.py:73 Detected image: image_id=bionic os=ubuntu release=bionic
2020-12-10 21:06:15 INFO      integration_testing:clouds.py:73 Detected image: image_id=bionic os=ubuntu release=bionic
2020-12-10 21:06:26 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=bionic
PLATFORM=lxd_container
RUN_UNSTABLE=False
2020-12-10 21:06:26 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_container
2020-12-10 21:06:26 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:0cb978a481d837eae60e40250faee5cbbff7d5325cac859fbd6222ebee0f1896
user_data=None
wait=False
2020-12-10 21:07:00 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:07:01 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:07:11 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:07:11 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:07:12 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:07:13 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=advanced-spider)
2020-12-10 21:07:13 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-10 21:07:13 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-10 21:07:31 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-10 21:07:32 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~18.04.1
2020-12-10 21:07:32 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:32 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:07:33 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:33 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:07:33 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:34 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:08:56 INFO      integration_testing:instances.py:117 Created new image: local:advanced-spider-snapshot
2020-12-10 21:08:57 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-10 21:08:57 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:advanced-spider-snapshot
user_data=None
wait=False
2020-12-10 21:09:07 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:09:08 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:09:08 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:09:15 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=active-wallaby)
------------------------------------------ live log call -------------------------------------------
2020-12-10 21:09:15 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'mkdir /var/tmp/test_seed_dir && touch /var/tmp/test_seed_dir/user-data && touch /var/tmp/test_seed_dir/meta-data && echo '"'"'seedfrom: /var/tmp/test_seed_dir/'"'"' > /var/lib/cloud/seed/nocloud-net/meta-data'
2020-12-10 21:09:15 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'mv /var/tmp/e3311b27-03b4-45ed-b924-30cf6979c5c2.tmp /var/tmp/test_seed_dir/vendor-data'
2020-12-10 21:09:16 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init clean --logs'
2020-12-10 21:09:19 INFO      integration_testing:instances.py:67 Instance restarted; waiting for boot
2020-12-10 21:09:19 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:09:19 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:09:20 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:09:27 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ls /var/tmp'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-10 21:09:29 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:advanced-spider-snapshot


========================================= warnings summary =========================================
tests/integration_tests/bugs/test_gh570.py::test_nocloud_seedfrom_vendordata
  /tmp/integration-tests-tox/bionic/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= 1 passed, 1 warning in 194.53s (0:03:14) =============================
```

focal:

```
GLOB sdist-make: /home/daniel/dev/cloud-init/setup.py
focal inst-nodeps: /tmp/integration-tests-tox/.tmp/package/4/cloud-init-20.4.zip
focal installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/4/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@324763289c9a38fc9ac7ec524acb9eb11c7d6c13,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==19.1.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
focal run-test-pre: PYTHONHASHSEED='426615725'
focal run-test: commands[0] | /tmp/integration-tests-tox/focal/bin/python -m pytest --log-cli-level=INFO bugs/test_gh570.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/focal/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item

bugs/test_gh570.py::test_nocloud_seedfrom_vendordata
------------------------------------------ live log setup ------------------------------------------
2020-12-10 21:06:27 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
2020-12-10 21:06:27 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
2020-12-10 21:06:37 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=focal
PLATFORM=lxd_container
RUN_UNSTABLE=False
2020-12-10 21:06:37 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_container
2020-12-10 21:06:37 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:3e9403fe7645000fc49ec89bca056c7fd53e9a142a3a9054ee02c13a2f14b6d0
user_data=None
wait=False
2020-12-10 21:07:02 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:07:02 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:07:13 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:07:13 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:07:14 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:07:20 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=logical-weevil)
2020-12-10 21:07:20 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-10 21:07:20 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-10 21:07:38 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-10 21:07:39 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~20.04.1
2020-12-10 21:07:39 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:39 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:07:40 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:40 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:07:40 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:41 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:10:41 INFO      integration_testing:instances.py:117 Created new image: local:logical-weevil-snapshot
2020-12-10 21:10:42 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-10 21:10:42 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:logical-weevil-snapshot
user_data=None
wait=False
2020-12-10 21:10:57 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:10:57 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:10:58 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:11:02 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=wired-donkey)
------------------------------------------ live log call -------------------------------------------
2020-12-10 21:11:02 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'mkdir /var/tmp/test_seed_dir && touch /var/tmp/test_seed_dir/user-data && touch /var/tmp/test_seed_dir/meta-data && echo '"'"'seedfrom: /var/tmp/test_seed_dir/'"'"' > /var/lib/cloud/seed/nocloud-net/meta-data'
2020-12-10 21:11:03 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'mv /var/tmp/aa49bd7b-507c-4f1b-8889-a657e13933e2.tmp /var/tmp/test_seed_dir/vendor-data'
2020-12-10 21:11:03 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init clean --logs'
2020-12-10 21:11:06 INFO      integration_testing:instances.py:67 Instance restarted; waiting for boot
2020-12-10 21:11:06 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:11:06 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:11:06 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:11:10 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ls /var/tmp'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-10 21:11:12 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:logical-weevil-snapshot


========================================= warnings summary =========================================
tests/integration_tests/bugs/test_gh570.py::test_nocloud_seedfrom_vendordata
  /tmp/integration-tests-tox/focal/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= 1 passed, 1 warning in 286.07s (0:04:46) =============================
```

groovy:

```
GLOB sdist-make: /home/daniel/dev/cloud-init/setup.py
groovy inst-nodeps: /tmp/integration-tests-tox/.tmp/package/3/cloud-init-20.4.zip
groovy installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/3/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@d1c63026c76ed3ef02dc21982f9f7eeea2606f2a,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==20.0.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
groovy run-test-pre: PYTHONHASHSEED='2609166704'
groovy run-test: commands[0] | /tmp/integration-tests-tox/groovy/bin/python -m pytest --log-cli-level=INFO bugs/test_gh570.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/groovy/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item

bugs/test_gh570.py::test_nocloud_seedfrom_vendordata
------------------------------------------ live log setup ------------------------------------------
2020-12-10 21:06:19 INFO      integration_testing:clouds.py:73 Detected image: image_id=groovy os=ubuntu release=groovy
2020-12-10 21:06:19 INFO      integration_testing:clouds.py:73 Detected image: image_id=groovy os=ubuntu release=groovy
2020-12-10 21:06:30 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=groovy
PLATFORM=lxd_container
RUN_UNSTABLE=False
2020-12-10 21:06:32 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_container
2020-12-10 21:06:32 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:bac1692e9ec7f5c5cee35d149ca789121bed238c1182df2134b5aefa3977f3e0
user_data=None
wait=False
2020-12-10 21:07:01 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:07:01 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:07:11 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:07:12 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:07:12 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:07:14 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=climbing-drum)
2020-12-10 21:07:14 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-10 21:07:14 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-10 21:07:33 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-10 21:07:34 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~20.10.1
2020-12-10 21:07:34 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:34 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:07:35 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:35 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:07:36 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 21:07:36 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 21:09:48 INFO      integration_testing:instances.py:117 Created new image: local:climbing-drum-snapshot
2020-12-10 21:09:49 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-10 21:09:49 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:climbing-drum-snapshot
user_data=None
wait=False
2020-12-10 21:10:03 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:10:04 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:10:04 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:10:10 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=fast-prawn)
------------------------------------------ live log call -------------------------------------------
2020-12-10 21:10:10 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'mkdir /var/tmp/test_seed_dir && touch /var/tmp/test_seed_dir/user-data && touch /var/tmp/test_seed_dir/meta-data && echo '"'"'seedfrom: /var/tmp/test_seed_dir/'"'"' > /var/lib/cloud/seed/nocloud-net/meta-data'
2020-12-10 21:10:11 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'mv /var/tmp/37e674a1-73a1-4459-888d-d9d774ac0372.tmp /var/tmp/test_seed_dir/vendor-data'
2020-12-10 21:10:11 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init clean --logs'
2020-12-10 21:10:13 INFO      integration_testing:instances.py:67 Instance restarted; waiting for boot
2020-12-10 21:10:13 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 21:10:14 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 21:10:14 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 21:10:19 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ls /var/tmp'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-10 21:10:22 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:climbing-drum-snapshot


========================================= warnings summary =========================================
tests/integration_tests/bugs/test_gh570.py::test_nocloud_seedfrom_vendordata
  /tmp/integration-tests-tox/groovy/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= 1 passed, 1 warning in 242.58s (0:04:02) =============================
```

[Regression Potential]

This change affects only the NoCloud and OVF datasources, with similar changes
in each.  Each will now read an additional file from their seeds, if available,
and apply any configuration therein to the system.  Very few existing seeds
have vendor-data (because it hasn't been supported previously), but any that
_do_ will now have that vendor-data applied; this, however, will only happen on
first boot.
