https://github.com/canonical/cloud-init/commit/a5484d02973e5710442c11e1dc6b1153695c9a59

=== Begin SRU Template ===
[Impact]
ca_certs support was added for RHEL. This included a refactor of the code
affecting Ubuntu.

[Test Case]
There is an upstream test for this bug:
https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/modules/test_ca_certs.py

=== Xenial ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 2 items

tests/integration_tests/modules/test_ca_certs.py::TestCaCerts::test_certs_updated Detected image: image_id=xenial os=ubuntu release=xenial

-------------------------------- live log setup --------------------------------
2021-03-25 19:30:46 INFO      integration_testing:clouds.py:87 Detected image: image_id=xenial os=ubuntu release=xenial
Detected image: image_id=xenial os=ubuntu release=xenial
2021-03-25 19:30:46 INFO      integration_testing:clouds.py:87 Detected image: image_id=xenial os=ubuntu release=xenial
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=xenial
PLATFORM=lxd_vm
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-25 19:30:46 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=xenial
PLATFORM=lxd_vm
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for lxd_vm
2021-03-25 19:30:46 INFO      integration_testing:conftest.py:156 Setting up environment for lxd_vm
Launching instance with launch_kwargs:
user_data=None
image_id=images:ubuntu/16.04/cloud
2021-03-25 19:30:46 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=None
image_id=images:ubuntu/16.04/cloud
The profile named pycloudlib-vm-xenial-v1 already exists
['lxc', 'init', 'images:ubuntu/16.04/cloud', '--profile', 'pycloudlib-vm-xenial-v1', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n', '--vm']
2021-03-25 19:30:48 INFO      pycloudlib.instance:instance.py:161 executing: sh -c whoami
2021-03-25 19:31:05 INFO      pycloudlib.instance:instance.py:338 [Errno None] Unable to connect to port 22 on 10.37.179.18
Retrying SSH connection to ubuntu@10.37.179.18:22 (583s left)
2021-03-25 19:31:07 INFO      pycloudlib.instance:instance.py:338 [Errno None] Unable to connect to port 22 on 10.37.179.18
Retrying SSH connection to ubuntu@10.37.179.18:22 (581s left)
2021-03-25 19:31:08 INFO      pycloudlib.instance:instance.py:338 [Errno None] Unable to connect to port 22 on 10.37.179.18
Retrying SSH connection to ubuntu@10.37.179.18:22 (580s left)
2021-03-25 19:31:10 INFO      pycloudlib.instance:instance.py:338 [Errno None] Unable to connect to port 22 on 10.37.179.18
Retrying SSH connection to ubuntu@10.37.179.18:22 (578s left)
2021-03-25 19:31:11 INFO      pycloudlib.instance:instance.py:338 [Errno None] Unable to connect to port 22 on 10.37.179.18
Retrying SSH connection to ubuntu@10.37.179.18:22 (577s left)
2021-03-25 19:31:12 INFO      pycloudlib.instance:instance.py:338 [Errno None] Unable to connect to port 22 on 10.37.179.18
Retrying SSH connection to ubuntu@10.37.179.18:22 (576s left)
2021-03-25 19:31:14 INFO      pycloudlib.instance:instance.py:338 [Errno None] Unable to connect to port 22 on 10.37.179.18
Retrying SSH connection to ubuntu@10.37.179.18:22 (574s left)
2021-03-25 19:31:15 INFO      pycloudlib.instance:instance.py:338 [Errno None] Unable to connect to port 22 on 10.37.179.18
Retrying SSH connection to ubuntu@10.37.179.18:22 (573s left)
2021-03-25 19:31:17 INFO      pycloudlib.instance:instance.py:338 [Errno None] Unable to connect to port 22 on 10.37.179.18
Retrying SSH connection to ubuntu@10.37.179.18:22 (571s left)
2021-03-25 19:31:18 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.2p2)
2021-03-25 19:31:18 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-25 19:31:18 INFO      pycloudlib.instance:instance.py:161 executing: sh -c 'cloud-init status --help'
2021-03-25 19:31:18 INFO      pycloudlib.instance:instance.py:161 executing: cloud-init status --wait --long
Launched instance: LXDInstance(name=refined-escargot)
2021-03-25 19:31:19 INFO      integration_testing:clouds.py:171 Launched instance: LXDInstance(name=refined-escargot)
2021-03-25 19:31:19 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~16.04.1
2021-03-25 19:31:19 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~16.04.1
2021-03-25 19:31:19 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
Installing proposed image
2021-03-25 19:31:19 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-25 19:31:19 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-25 19:31:26 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-25 19:31:26 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-25 19:31:26 INFO      pycloudlib.instance:instance.py:161 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 19:31:27 INFO      pycloudlib.instance:instance.py:161 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-25 19:31:27 INFO      pycloudlib.instance:instance.py:161 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 19:31:27 INFO      pycloudlib.instance:instance.py:161 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-25 19:31:27 INFO      pycloudlib.instance:instance.py:161 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 19:31:27 INFO      pycloudlib.instance:instance.py:161 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: local:refined-escargot-snapshot
2021-03-25 19:32:16 INFO      integration_testing:instances.py:113 Created new image: local:refined-escargot-snapshot
Done with environment setup
2021-03-25 19:32:17 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
user_data=#cloud-config
ca-certs:
  remove-defaults: true
  trusted:
    - |
      -----BEGIN CERTIFICATE-----
      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx
      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP
      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl
      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW
      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz
      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93
      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl
      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG
      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc
      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ
      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX
      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6
      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2
      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S
      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o
      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4
      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF
      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1
      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3
      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT
      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5
      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3
      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr
      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf
      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ
      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM
      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L
      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT
      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro
      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586
      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l
      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i
      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==
      -----END CERTIFICATE-----

image_id=local:refined-escargot-snapshot
2021-03-25 19:32:17 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=#cloud-config
ca-certs:
  remove-defaults: true
  trusted:
    - |
      -----BEGIN CERTIFICATE-----
      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx
      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP
      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl
      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW
      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz
      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93
      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl
      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG
      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc
      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ
      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX
      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6
      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2
      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S
      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o
      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4
      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF
      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1
      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3
      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT
      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5
      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3
      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr
      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf
      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ
      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM
      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L
      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT
      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro
      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586
      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l
      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i
      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==
      -----END CERTIFICATE-----

image_id=local:refined-escargot-snapshot
['lxc', 'init', 'local:refined-escargot-snapshot', '--profile', 'pycloudlib-vm-xenial-v1', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n', '--config', 'user.user-data=#cloud-config\nca-certs:\n  remove-defaults: true\n  trusted:\n    - |\n      -----BEGIN CERTIFICATE-----\n      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx\n      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP\n      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl\n      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW\n      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz\n      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93\n      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl\n      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG\n      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc\n      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ\n      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX\n      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6\n      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2\n      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S\n      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o\n      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4\n      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF\n      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1\n      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3\n      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT\n      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5\n      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3\n      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr\n      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf\n      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ\n      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM\n      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L\n      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT\n      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro\n      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586\n      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l\n      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i\n      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==\n      -----END CERTIFICATE-----\n', '--vm']
2021-03-25 19:33:09 INFO      pycloudlib.instance:instance.py:161 executing: sh -c whoami
2021-03-25 19:33:26 INFO      pycloudlib.instance:instance.py:338 [Errno None] Unable to connect to port 22 on 10.37.179.18
Retrying SSH connection to ubuntu@10.37.179.18:22 (582s left)
2021-03-25 19:33:27 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.2p2)
2021-03-25 19:33:28 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-25 19:33:28 INFO      pycloudlib.instance:instance.py:161 executing: sh -c 'cloud-init status --help'
2021-03-25 19:33:28 INFO      pycloudlib.instance:instance.py:161 executing: cloud-init status --wait --long
Launched instance: LXDInstance(name=positive-marmot)
2021-03-25 19:33:30 INFO      integration_testing:clouds.py:171 Launched instance: LXDInstance(name=positive-marmot)
2021-03-25 19:33:30 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-25 19:33:30 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-25 19:33:30 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
-------------------------------- live log call ---------------------------------
2021-03-25 19:33:30 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- ls -1 /etc/ssl/certs
2021-03-25 19:33:30 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- readlink /etc/ssl/certs/39ff795e.0
2021-03-25 19:33:31 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- readlink /etc/ssl/certs/a535c1f3.0
2021-03-25 19:33:31 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- readlink /etc/ssl/certs/ca-certificates.crt
2021-03-25 19:33:31 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- readlink /etc/ssl/certs/cloud-init-ca-certs.pem
PASSED
tests/integration_tests/modules/test_ca_certs.py::TestCaCerts::test_cert_installed Detected image: image_id=xenial os=ubuntu release=xenial

-------------------------------- live log setup --------------------------------
2021-03-25 19:33:31 INFO      integration_testing:clouds.py:87 Detected image: image_id=xenial os=ubuntu release=xenial
-------------------------------- live log call ---------------------------------
2021-03-25 19:33:31 INFO      pycloudlib.instance:instance.py:161 executing: sudo -- sh -c 'sha256sum /etc/ssl/certs/ca-certificates.crt'
PASSEDDeleting snapshot image created for this testrun: local:refined-escargot-snapshot

------------------------------ live log teardown -------------------------------
2021-03-25 19:33:31 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: local:refined-escargot-snapshot


======================== 2 passed in 165.85s (0:02:45) =========================

=== Bionic ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 2 items

tests/integration_tests/modules/test_ca_certs.py::TestCaCerts::test_certs_updated Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------- live log setup --------------------------------
2021-03-25 19:50:56 INFO      integration_testing:clouds.py:87 Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
2021-03-25 19:50:56 INFO      integration_testing:clouds.py:87 Detected image: image_id=bionic os=ubuntu release=bionic
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=bionic
PLATFORM=lxd_vm
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-25 19:51:16 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=bionic
PLATFORM=lxd_vm
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for lxd_vm
2021-03-25 19:51:16 INFO      integration_testing:conftest.py:156 Setting up environment for lxd_vm
Launching instance with launch_kwargs:
image_id=ubuntu:fa43cc40052fdeca5f21412e037187c06931f70dc5f46d19bf184ea741a87624
user_data=None
2021-03-25 19:51:16 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=ubuntu:fa43cc40052fdeca5f21412e037187c06931f70dc5f46d19bf184ea741a87624
user_data=None
['lxc', 'init', 'ubuntu:fa43cc40052fdeca5f21412e037187c06931f70dc5f46d19bf184ea741a87624', '--profile', 'pycloudlib-vm-bionic-v2', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n', '--vm']
2021-03-25 19:51:23 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-25 19:51:47 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.154
Retrying SSH connection to ubuntu@10.37.179.154:22 (576s left)
2021-03-25 19:51:49 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.154
Retrying SSH connection to ubuntu@10.37.179.154:22 (574s left)
2021-03-25 19:51:50 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.154
Retrying SSH connection to ubuntu@10.37.179.154:22 (573s left)
2021-03-25 19:51:51 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.154
Retrying SSH connection to ubuntu@10.37.179.154:22 (572s left)
2021-03-25 19:51:52 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-03-25 19:51:52 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-25 19:51:53 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-25 19:51:54 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: LXDInstance(name=central-moray)
2021-03-25 19:51:56 INFO      integration_testing:clouds.py:171 Launched instance: LXDInstance(name=central-moray)
2021-03-25 19:51:56 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
2021-03-25 19:51:56 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-03-25 19:51:56 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-25 19:51:56 ERROR     paramiko.transport:transport.py:1819 Socket exception: Connection reset by peer (104)
2021-03-25 19:51:57 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.154
Retrying SSH connection to ubuntu@10.37.179.154:22 (598s left)
2021-03-25 19:52:30 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-03-25 19:52:30 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~18.04.1
2021-03-25 19:52:31 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~18.04.1
2021-03-25 19:52:31 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210319
2021-03-25 19:52:31 INFO      integration_testing:clouds.py:181 image serial: 20210319
Installing proposed image
2021-03-25 19:52:31 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-25 19:52:31 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-25 19:52:57 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-25 19:52:57 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-25 19:52:57 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 19:52:57 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-25 19:52:57 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 19:52:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-25 19:52:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 19:52:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: local:central-moray-snapshot
2021-03-25 19:54:16 INFO      integration_testing:instances.py:113 Created new image: local:central-moray-snapshot
Done with environment setup
2021-03-25 19:54:16 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=local:central-moray-snapshot
user_data=#cloud-config
ca-certs:
  remove-defaults: true
  trusted:
    - |
      -----BEGIN CERTIFICATE-----
      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx
      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP
      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl
      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW
      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz
      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93
      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl
      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG
      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc
      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ
      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX
      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6
      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2
      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S
      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o
      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4
      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF
      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1
      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3
      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT
      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5
      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3
      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr
      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf
      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ
      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM
      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L
      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT
      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro
      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586
      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l
      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i
      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==
      -----END CERTIFICATE-----

2021-03-25 19:54:16 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=local:central-moray-snapshot
user_data=#cloud-config
ca-certs:
  remove-defaults: true
  trusted:
    - |
      -----BEGIN CERTIFICATE-----
      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx
      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP
      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl
      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW
      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz
      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93
      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl
      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG
      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc
      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ
      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX
      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6
      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2
      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S
      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o
      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4
      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF
      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1
      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3
      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT
      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5
      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3
      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr
      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf
      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ
      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM
      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L
      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT
      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro
      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586
      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l
      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i
      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==
      -----END CERTIFICATE-----

['lxc', 'init', 'local:central-moray-snapshot', '--profile', 'pycloudlib-vm-bionic-v2', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n', '--config', 'user.user-data=#cloud-config\nca-certs:\n  remove-defaults: true\n  trusted:\n    - |\n      -----BEGIN CERTIFICATE-----\n      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx\n      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP\n      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl\n      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW\n      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz\n      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93\n      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl\n      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG\n      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc\n      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ\n      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX\n      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6\n      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2\n      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S\n      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o\n      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4\n      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF\n      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1\n      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3\n      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT\n      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5\n      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3\n      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr\n      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf\n      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ\n      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM\n      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L\n      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT\n      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro\n      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586\n      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l\n      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i\n      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==\n      -----END CERTIFICATE-----\n', '--vm']
2021-03-25 19:55:24 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-25 19:56:13 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.122
Retrying SSH connection to ubuntu@10.37.179.122:22 (551s left)
2021-03-25 19:56:14 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.122
Retrying SSH connection to ubuntu@10.37.179.122:22 (550s left)
2021-03-25 19:56:15 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-03-25 19:56:15 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-25 19:56:17 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-25 19:56:17 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: LXDInstance(name=coherent-walrus)
2021-03-25 19:56:21 INFO      integration_testing:clouds.py:171 Launched instance: LXDInstance(name=coherent-walrus)
2021-03-25 19:56:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-25 19:56:21 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-25 19:56:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210319
2021-03-25 19:56:21 INFO      integration_testing:clouds.py:181 image serial: 20210319
-------------------------------- live log call ---------------------------------
2021-03-25 19:56:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- ls -1 /etc/ssl/certs
2021-03-25 19:56:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- readlink /etc/ssl/certs/a535c1f3.0
2021-03-25 19:56:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- readlink /etc/ssl/certs/ca-certificates.crt
2021-03-25 19:56:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- readlink /etc/ssl/certs/cloud-init-ca-certs.pem
PASSED
tests/integration_tests/modules/test_ca_certs.py::TestCaCerts::test_cert_installed Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------- live log setup --------------------------------
2021-03-25 19:56:21 INFO      integration_testing:clouds.py:87 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-03-25 19:56:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'sha256sum /etc/ssl/certs/ca-certificates.crt'
PASSEDDeleting snapshot image created for this testrun: local:central-moray-snapshot

------------------------------ live log teardown -------------------------------
2021-03-25 19:56:22 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: local:central-moray-snapshot


======================== 2 passed in 326.07s (0:05:26) =========================


=== Focal ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 2 items

tests/integration_tests/modules/test_ca_certs.py::TestCaCerts::test_certs_updated Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-03-25 20:19:01 INFO      integration_testing:clouds.py:87 Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
2021-03-25 20:19:01 INFO      integration_testing:clouds.py:87 Detected image: image_id=focal os=ubuntu release=focal
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=focal
PLATFORM=lxd_vm
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-25 20:19:21 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=focal
PLATFORM=lxd_vm
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for lxd_vm
2021-03-25 20:19:21 INFO      integration_testing:conftest.py:156 Setting up environment for lxd_vm
Launching instance with launch_kwargs:
image_id=ubuntu:a56b7ffd973b320cc408f47b6e4017b4e7a8d35df4b53e30096faf00870834dd
user_data=None
2021-03-25 20:19:21 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=ubuntu:a56b7ffd973b320cc408f47b6e4017b4e7a8d35df4b53e30096faf00870834dd
user_data=None
The profile named pycloudlib-vm-focal-v2 already exists
['lxc', 'init', 'ubuntu:a56b7ffd973b320cc408f47b6e4017b4e7a8d35df4b53e30096faf00870834dd', '--profile', 'pycloudlib-vm-focal-v2', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n', '--vm']
2021-03-25 20:19:29 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-25 20:19:50 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.243
Retrying SSH connection to ubuntu@10.37.179.243:22 (578s left)
2021-03-25 20:19:51 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.243
Retrying SSH connection to ubuntu@10.37.179.243:22 (577s left)
2021-03-25 20:19:53 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.243
Retrying SSH connection to ubuntu@10.37.179.243:22 (576s left)
2021-03-25 20:19:54 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.243
Retrying SSH connection to ubuntu@10.37.179.243:22 (574s left)
2021-03-25 20:19:55 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-03-25 20:19:55 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-25 20:19:56 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-25 20:19:57 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: LXDInstance(name=harmless-tetra)
2021-03-25 20:20:00 INFO      integration_testing:clouds.py:171 Launched instance: LXDInstance(name=harmless-tetra)
2021-03-25 20:20:00 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.04.1
2021-03-25 20:20:00 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.04.1
2021-03-25 20:20:00 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210323
2021-03-25 20:20:00 INFO      integration_testing:clouds.py:181 image serial: 20210323
Installing proposed image
2021-03-25 20:20:00 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-25 20:20:00 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-25 20:20:24 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-25 20:20:24 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-25 20:20:24 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 20:20:24 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-25 20:20:24 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 20:20:24 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-25 20:20:25 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 20:20:25 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: local:harmless-tetra-snapshot
2021-03-25 20:21:57 INFO      integration_testing:instances.py:113 Created new image: local:harmless-tetra-snapshot
Done with environment setup
2021-03-25 20:21:58 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=local:harmless-tetra-snapshot
user_data=#cloud-config
ca-certs:
  remove-defaults: true
  trusted:
    - |
      -----BEGIN CERTIFICATE-----
      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx
      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP
      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl
      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW
      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz
      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93
      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl
      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG
      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc
      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ
      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX
      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6
      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2
      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S
      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o
      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4
      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF
      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1
      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3
      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT
      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5
      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3
      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr
      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf
      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ
      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM
      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L
      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT
      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro
      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586
      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l
      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i
      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==
      -----END CERTIFICATE-----

2021-03-25 20:21:58 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=local:harmless-tetra-snapshot
user_data=#cloud-config
ca-certs:
  remove-defaults: true
  trusted:
    - |
      -----BEGIN CERTIFICATE-----
      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx
      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP
      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl
      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW
      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz
      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93
      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl
      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG
      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc
      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ
      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX
      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6
      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2
      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S
      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o
      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4
      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF
      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1
      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3
      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT
      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5
      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3
      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr
      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf
      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ
      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM
      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L
      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT
      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro
      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586
      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l
      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i
      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==
      -----END CERTIFICATE-----

['lxc', 'init', 'local:harmless-tetra-snapshot', '--profile', 'pycloudlib-vm-focal-v2', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n', '--config', 'user.user-data=#cloud-config\nca-certs:\n  remove-defaults: true\n  trusted:\n    - |\n      -----BEGIN CERTIFICATE-----\n      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx\n      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP\n      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl\n      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW\n      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz\n      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93\n      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl\n      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG\n      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc\n      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ\n      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX\n      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6\n      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2\n      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S\n      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o\n      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4\n      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF\n      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1\n      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3\n      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT\n      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5\n      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3\n      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr\n      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf\n      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ\n      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM\n      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L\n      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT\n      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro\n      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586\n      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l\n      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i\n      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==\n      -----END CERTIFICATE-----\n', '--vm']
2021-03-25 20:23:01 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-25 20:23:21 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.112
Retrying SSH connection to ubuntu@10.37.179.112:22 (579s left)
2021-03-25 20:23:23 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.112
Retrying SSH connection to ubuntu@10.37.179.112:22 (578s left)
2021-03-25 20:23:24 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-03-25 20:23:24 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-25 20:23:26 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-25 20:23:26 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: LXDInstance(name=patient-firefly)
2021-03-25 20:23:29 INFO      integration_testing:clouds.py:171 Launched instance: LXDInstance(name=patient-firefly)
2021-03-25 20:23:29 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-25 20:23:29 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-25 20:23:29 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210323
2021-03-25 20:23:29 INFO      integration_testing:clouds.py:181 image serial: 20210323
-------------------------------- live log call ---------------------------------
2021-03-25 20:23:29 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- ls -1 /etc/ssl/certs
2021-03-25 20:23:29 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- readlink /etc/ssl/certs/a535c1f3.0
2021-03-25 20:23:29 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- readlink /etc/ssl/certs/ca-certificates.crt
2021-03-25 20:23:30 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- readlink /etc/ssl/certs/cloud-init-ca-certs.pem
PASSED
tests/integration_tests/modules/test_ca_certs.py::TestCaCerts::test_cert_installed Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-03-25 20:23:30 INFO      integration_testing:clouds.py:87 Detected image: image_id=focal os=ubuntu release=focal
-------------------------------- live log call ---------------------------------
2021-03-25 20:23:30 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'sha256sum /etc/ssl/certs/ca-certificates.crt'
PASSEDDeleting snapshot image created for this testrun: local:harmless-tetra-snapshot

------------------------------ live log teardown -------------------------------
2021-03-25 20:23:30 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: local:harmless-tetra-snapshot


======================== 2 passed in 269.59s (0:04:29) =========================


=== Groovy ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 2 items

tests/integration_tests/modules/test_ca_certs.py::TestCaCerts::test_certs_updated Detected image: image_id=groovy os=ubuntu release=groovy

-------------------------------- live log setup --------------------------------
2021-03-25 20:44:48 INFO      integration_testing:clouds.py:87 Detected image: image_id=groovy os=ubuntu release=groovy
Detected image: image_id=groovy os=ubuntu release=groovy
2021-03-25 20:44:48 INFO      integration_testing:clouds.py:87 Detected image: image_id=groovy os=ubuntu release=groovy
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=groovy
PLATFORM=lxd_vm
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-25 20:45:04 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=groovy
PLATFORM=lxd_vm
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for lxd_vm
2021-03-25 20:45:04 INFO      integration_testing:conftest.py:156 Setting up environment for lxd_vm
Launching instance with launch_kwargs:
user_data=None
image_id=ubuntu:08c31b98a026f237c3d991c70acf7fc64bbc9b4e4ecaca2b8083f11eddef48ec
2021-03-25 20:45:04 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=None
image_id=ubuntu:08c31b98a026f237c3d991c70acf7fc64bbc9b4e4ecaca2b8083f11eddef48ec
The profile named pycloudlib-vm-groovy-v2 already exists
['lxc', 'init', 'ubuntu:08c31b98a026f237c3d991c70acf7fc64bbc9b4e4ecaca2b8083f11eddef48ec', '--profile', 'pycloudlib-vm-groovy-v2', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n', '--vm']
2021-03-25 20:45:11 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-25 20:45:34 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.206
Retrying SSH connection to ubuntu@10.37.179.206:22 (577s left)
2021-03-25 20:45:35 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.206
Retrying SSH connection to ubuntu@10.37.179.206:22 (576s left)
2021-03-25 20:45:37 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.206
Retrying SSH connection to ubuntu@10.37.179.206:22 (574s left)
2021-03-25 20:45:38 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.3p1)
2021-03-25 20:45:38 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-25 20:45:40 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-25 20:45:41 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: LXDInstance(name=proven-gazelle)
2021-03-25 20:45:48 INFO      integration_testing:clouds.py:171 Launched instance: LXDInstance(name=proven-gazelle)
2021-03-25 20:45:48 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.10.1
2021-03-25 20:45:49 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.10.1
2021-03-25 20:45:49 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210323
2021-03-25 20:45:49 INFO      integration_testing:clouds.py:181 image serial: 20210323
Installing proposed image
2021-03-25 20:45:49 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-25 20:45:49 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-25 20:46:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-25 20:46:22 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-25 20:46:22 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 20:46:22 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-25 20:46:22 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 20:46:22 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-25 20:46:22 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-25 20:46:23 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: local:proven-gazelle-snapshot
2021-03-25 20:47:50 INFO      integration_testing:instances.py:113 Created new image: local:proven-gazelle-snapshot
Done with environment setup
2021-03-25 20:47:51 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
user_data=#cloud-config
ca-certs:
  remove-defaults: true
  trusted:
    - |
      -----BEGIN CERTIFICATE-----
      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx
      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP
      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl
      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW
      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz
      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93
      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl
      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG
      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc
      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ
      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX
      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6
      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2
      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S
      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o
      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4
      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF
      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1
      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3
      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT
      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5
      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3
      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr
      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf
      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ
      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM
      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L
      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT
      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro
      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586
      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l
      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i
      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==
      -----END CERTIFICATE-----

image_id=local:proven-gazelle-snapshot
2021-03-25 20:47:51 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=#cloud-config
ca-certs:
  remove-defaults: true
  trusted:
    - |
      -----BEGIN CERTIFICATE-----
      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx
      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP
      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl
      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW
      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz
      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93
      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl
      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG
      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc
      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ
      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX
      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6
      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2
      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S
      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o
      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4
      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF
      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1
      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3
      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT
      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5
      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3
      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr
      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf
      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ
      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM
      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L
      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT
      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro
      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586
      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l
      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i
      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==
      -----END CERTIFICATE-----

image_id=local:proven-gazelle-snapshot
['lxc', 'init', 'local:proven-gazelle-snapshot', '--profile', 'pycloudlib-vm-groovy-v2', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n', '--config', 'user.user-data=#cloud-config\nca-certs:\n  remove-defaults: true\n  trusted:\n    - |\n      -----BEGIN CERTIFICATE-----\n      MIIGJzCCBA+gAwIBAgIBATANBgkqhkiG9w0BAQUFADCBsjELMAkGA1UEBhMCRlIx\n      DzANBgNVBAgMBkFsc2FjZTETMBEGA1UEBwwKU3RyYXNib3VyZzEYMBYGA1UECgwP\n      d3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLDAdmcmVlbGFuMS0wKwYDVQQDDCRGcmVl\n      bGFuIFNhbXBsZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEW\n      E2NvbnRhY3RAZnJlZWxhbi5vcmcwHhcNMTIwNDI3MTAzMTE4WhcNMjIwNDI1MTAz\n      MTE4WjB+MQswCQYDVQQGEwJGUjEPMA0GA1UECAwGQWxzYWNlMRgwFgYDVQQKDA93\n      d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsMB2ZyZWVsYW4xDjAMBgNVBAMMBWFsaWNl\n      MSIwIAYJKoZIhvcNAQkBFhNjb250YWN0QGZyZWVsYW4ub3JnMIICIjANBgkqhkiG\n      9w0BAQEFAAOCAg8AMIICCgKCAgEA3W29+ID6194bH6ejLrIC4hb2Ugo8v6ZC+Mrc\n      k2dNYMNPjcOKABvxxEtBamnSaeU/IY7FC/giN622LEtV/3oDcrua0+yWuVafyxmZ\n      yTKUb4/GUgafRQPf/eiX9urWurtIK7XgNGFNUjYPq4dSJQPPhwCHE/LKAykWnZBX\n      RrX0Dq4XyApNku0IpjIjEXH+8ixE12wH8wt7DEvdO7T3N3CfUbaITl1qBX+Nm2Z6\n      q4Ag/u5rl8NJfXg71ZmXA3XOj7zFvpyapRIZcPmkvZYn7SMCp8dXyXHPdpSiIWL2\n      uB3KiO4JrUYvt2GzLBUThp+lNSZaZ/Q3yOaAAUkOx+1h08285Pi+P8lO+H2Xic4S\n      vMq1xtLg2bNoPC5KnbRfuFPuUD2/3dSiiragJ6uYDLOyWJDivKGt/72OVTEPAL9o\n      6T2pGZrwbQuiFGrGTMZOvWMSpQtNl+tCCXlT4mWqJDRwuMGrI4DnnGzt3IKqNwS4\n      Qyo9KqjMIPwnXZAmWPm3FOKe4sFwc5fpawKO01JZewDsYTDxVj+cwXwFxbE2yBiF\n      z2FAHwfopwaH35p3C6lkcgP2k/zgAlnBluzACUI+MKJ/G0gv/uAhj1OHJQ3L6kn1\n      SpvQ41/ueBjlunExqQSYD7GtZ1Kg8uOcq2r+WISE3Qc9MpQFFkUVllmgWGwYDuN3\n      Zsez95kCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNT\n      TCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFFlfyRO6G8y5qEFKikl5\n      ajb2fT7XMB8GA1UdIwQYMBaAFCNsLT0+KV14uGw+quK7Lh5sh/JTMA0GCSqGSIb3\n      DQEBBQUAA4ICAQAT5wJFPqervbja5+90iKxi1d0QVtVGB+z6aoAMuWK+qgi0vgvr\n      mu9ot2lvTSCSnRhjeiP0SIdqFMORmBtOCFk/kYDp9M/91b+vS+S9eAlxrNCB5VOf\n      PqxEPp/wv1rBcE4GBO/c6HcFon3F+oBYCsUQbZDKSSZxhDm3mj7pb67FNbZbJIzJ\n      70HDsRe2O04oiTx+h6g6pW3cOQMgIAvFgKN5Ex727K4230B0NIdGkzuj4KSML0NM\n      slSAcXZ41OoSKNjy44BVEZv0ZdxTDrRM4EwJtNyggFzmtTuV02nkUj1bYYYC5f0L\n      ADr6s0XMyaNk8twlWYlYDZ5uKDpVRVBfiGcq0uJIzIvemhuTrofh8pBQQNkPRDFT\n      Rq1iTo1Ihhl3/Fl1kXk1WR3jTjNb4jHX7lIoXwpwp767HAPKGhjQ9cFbnHMEtkro\n      RlJYdtRq5mccDtwT0GFyoJLLBZdHHMHJz0F9H7FNk2tTQQMhK5MVYwg+LIaee586\n      CQVqfbscp7evlgjLW98H+5zylRHAgoH2G79aHljNKMp9BOuq6SnEglEsiWGVtu2l\n      hnx8SB3sVJZHeer8f/UQQwqbAO+Kdy70NmbSaqaVtp8jOxLiidWkwSyRTsuU6D8i\n      DiH5uEqBXExjrj0FslxcVKdVj5glVcSmkLwZKbEU1OKwleT/iXFhvooWhQ==\n      -----END CERTIFICATE-----\n', '--vm']
2021-03-25 20:49:06 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-25 20:49:27 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.11
Retrying SSH connection to ubuntu@10.37.179.11:22 (579s left)
2021-03-25 20:49:28 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.11
Retrying SSH connection to ubuntu@10.37.179.11:22 (578s left)
2021-03-25 20:49:29 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.3p1)
2021-03-25 20:49:30 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-25 20:49:31 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-25 20:49:32 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: LXDInstance(name=artistic-ghoul)
2021-03-25 20:49:34 INFO      integration_testing:clouds.py:171 Launched instance: LXDInstance(name=artistic-ghoul)
2021-03-25 20:49:34 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-25 20:49:35 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-25 20:49:35 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210323
2021-03-25 20:49:35 INFO      integration_testing:clouds.py:181 image serial: 20210323
-------------------------------- live log call ---------------------------------
2021-03-25 20:49:35 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- ls -1 /etc/ssl/certs
2021-03-25 20:49:35 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- readlink /etc/ssl/certs/a535c1f3.0
2021-03-25 20:49:35 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- readlink /etc/ssl/certs/ca-certificates.crt
2021-03-25 20:49:35 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- readlink /etc/ssl/certs/cloud-init-ca-certs.pem
PASSED
tests/integration_tests/modules/test_ca_certs.py::TestCaCerts::test_cert_installed Detected image: image_id=groovy os=ubuntu release=groovy

-------------------------------- live log setup --------------------------------
2021-03-25 20:49:35 INFO      integration_testing:clouds.py:87 Detected image: image_id=groovy os=ubuntu release=groovy
-------------------------------- live log call ---------------------------------
2021-03-25 20:49:35 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'sha256sum /etc/ssl/certs/ca-certificates.crt'
PASSEDDeleting snapshot image created for this testrun: local:proven-gazelle-snapshot

------------------------------ live log teardown -------------------------------
2021-03-25 20:49:35 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: local:proven-gazelle-snapshot


======================== 2 passed in 287.46s (0:04:47) =========================


[Regression Potential]
If a bug was introduced as part of the refactor, some aspect of writing or
linking ca-certs could no longer work.
