https://github.com/canonical/cloud-init/commit/a64b73808857fa7b4f262422ce2c87eedbce10d5

=== Begin SRU Template ===
[Impact]
For VM SKUs that come with
ephemeral resource disks, the Azure platform guarantees that
the ephemeral resource disk is attached to the VM before
the VM is booted. For VM SKUs that do not come with
ephemeral resource disks, cloud-init currently attempts
to wait and set up a non-existent ephemeral resource
disk, which wastes boot time. It also causes disk setup
modules to fail.

This has been changed to only setup and merge in default Azure cloud
ephemeral disk configs if the ephemeral disk exists

[Test Case]
There is an upstream test for this bug:
https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/bugs/test_lp1901011.py

=== Xenial ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 2 items

tests/integration_tests/bugs/test_lp1901011.py::test_ephemeral[Standard_DS1_v2-True] Detected image: image_id=xenial os=ubuntu release=xenial

-------------------------------- live log setup --------------------------------
2021-03-26 21:10:44 INFO      integration_testing:clouds.py:87 Detected image: image_id=xenial os=ubuntu release=xenial
Detected image: image_id=xenial os=ubuntu release=xenial
2021-03-26 21:10:44 INFO      integration_testing:clouds.py:87 Detected image: image_id=xenial os=ubuntu release=xenial
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=xenial
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-26 21:10:44 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=xenial
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for azure
2021-03-26 21:10:44 INFO      integration_testing:conftest.py:156 Setting up environment for azure
Launching instance with launch_kwargs:
image_id=Canonical:UbuntuServer:16.04-DAILY-LTS
user_data=None
2021-03-26 21:10:44 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=Canonical:UbuntuServer:16.04-DAILY-LTS
user_data=None
2021-03-26 21:12:32 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:12:32 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.2p2)
2021-03-26 21:12:32 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:12:33 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:12:33 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fd8741aa4a8>
2021-03-26 21:12:34 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fd8741aa4a8>
2021-03-26 21:12:34 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~16.04.1
2021-03-26 21:12:34 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~16.04.1
2021-03-26 21:12:34 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210316
2021-03-26 21:12:34 INFO      integration_testing:clouds.py:181 image serial: 20210316
Installing proposed image
2021-03-26 21:12:34 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-26 21:12:34 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-26 21:12:57 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:12:57 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:12:57 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:12:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:12:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:12:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:12:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo waagent -deprovision+user -force'
Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161044-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161044-image
2021-03-26 21:14:01 INFO      integration_testing:instances.py:113 Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161044-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161044-image
Done with environment setup
2021-03-26 21:14:41 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161044-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161044-image
user_data=None
instance_type=Standard_DS1_v2
-------------------------------- live log call ---------------------------------
2021-03-26 21:14:41 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161044-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161044-image
user_data=None
instance_type=Standard_DS1_v2
2021-03-26 21:15:28 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:15:28 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.2p2)
2021-03-26 21:15:28 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:15:29 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:15:29 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fd8738b2dd8>
2021-03-26 21:15:30 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fd8738b2dd8>
2021-03-26 21:15:30 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:15:30 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:15:30 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210316
2021-03-26 21:15:30 INFO      integration_testing:clouds.py:181 image serial: 20210316
2021-03-26 21:15:30 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-03-26 21:15:30 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'ls /dev/disk/cloud'
2021-03-26 21:15:31 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'lsblk -pPo NAME,TYPE,MOUNTPOINT'
2021-03-26 21:15:31 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_root-part1'
2021-03-26 21:15:31 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_resource-part1'
PASSED
tests/integration_tests/bugs/test_lp1901011.py::test_ephemeral[Standard_D2s_v4-False] Detected image: image_id=xenial os=ubuntu release=xenial

-------------------------------- live log setup --------------------------------
2021-03-26 21:16:11 INFO      integration_testing:clouds.py:87 Detected image: image_id=xenial os=ubuntu release=xenial
Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161044-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161044-image
user_data=None
instance_type=Standard_D2s_v4
-------------------------------- live log call ---------------------------------
2021-03-26 21:16:11 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161044-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161044-image
user_data=None
instance_type=Standard_D2s_v4
2021-03-26 21:16:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:16:58 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.2p2)
2021-03-26 21:16:59 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:16:59 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:17:00 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fd8746d74e0>
2021-03-26 21:17:00 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fd8746d74e0>
2021-03-26 21:17:00 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:17:00 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:17:00 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210316
2021-03-26 21:17:01 INFO      integration_testing:clouds.py:181 image serial: 20210316
2021-03-26 21:17:01 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-03-26 21:17:01 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'ls /dev/disk/cloud'
2021-03-26 21:17:01 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'lsblk -pPo NAME,TYPE,MOUNTPOINT'
2021-03-26 21:17:01 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_root-part1'
PASSEDDeleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161044-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161044-image

------------------------------ live log teardown -------------------------------
2021-03-26 21:17:42 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161044-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161044-image


======================== 2 passed in 418.82s (0:06:58) =========================


=== Bionic ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 2 items

tests/integration_tests/bugs/test_lp1901011.py::test_ephemeral[Standard_DS1_v2-True] Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------- live log setup --------------------------------
2021-03-26 21:24:43 INFO      integration_testing:clouds.py:87 Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
2021-03-26 21:24:44 INFO      integration_testing:clouds.py:87 Detected image: image_id=bionic os=ubuntu release=bionic
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=bionic
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-26 21:24:44 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=bionic
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for azure
2021-03-26 21:24:44 INFO      integration_testing:conftest.py:156 Setting up environment for azure
Launching instance with launch_kwargs:
user_data=None
image_id=Canonical:UbuntuServer:18.04-DAILY-LTS
2021-03-26 21:24:44 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=None
image_id=Canonical:UbuntuServer:18.04-DAILY-LTS
2021-03-26 21:26:15 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:26:15 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-03-26 21:26:15 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:26:17 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:26:19 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f3359ef4860>
2021-03-26 21:26:19 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f3359ef4860>
2021-03-26 21:26:19 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~18.04.1
2021-03-26 21:26:20 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~18.04.1
2021-03-26 21:26:20 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:26:20 INFO      integration_testing:clouds.py:181 image serial: 20210325
Installing proposed image
2021-03-26 21:26:20 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-26 21:26:20 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-26 21:26:42 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-26 21:26:43 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-26 21:26:43 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:26:43 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:26:44 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:26:44 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:26:44 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo waagent -deprovision+user -force'
Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-162443-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-162444-image
2021-03-26 21:27:47 INFO      integration_testing:instances.py:113 Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-162443-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-162444-image
Done with environment setup
2021-03-26 21:28:27 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
instance_type=Standard_DS1_v2
user_data=None
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-162443-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-162444-image
-------------------------------- live log call ---------------------------------
2021-03-26 21:28:27 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
instance_type=Standard_DS1_v2
user_data=None
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-162443-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-162444-image
2021-03-26 21:29:14 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:29:14 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-03-26 21:29:14 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:29:18 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:29:19 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f33590eac50>
2021-03-26 21:29:20 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f33590eac50>
2021-03-26 21:29:20 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-26 21:29:20 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-26 21:29:20 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:29:20 INFO      integration_testing:clouds.py:181 image serial: 20210325
2021-03-26 21:29:20 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-03-26 21:29:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'ls /dev/disk/cloud'
2021-03-26 21:29:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'lsblk -pPo NAME,TYPE,MOUNTPOINT'
2021-03-26 21:29:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_root-part1'
2021-03-26 21:29:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_resource-part1'
PASSED
tests/integration_tests/bugs/test_lp1901011.py::test_ephemeral[Standard_D2s_v4-False] Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------- live log setup --------------------------------
2021-03-26 21:30:02 INFO      integration_testing:clouds.py:87 Detected image: image_id=bionic os=ubuntu release=bionic
Launching instance with launch_kwargs:
instance_type=Standard_D2s_v4
user_data=None
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-162443-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-162444-image
-------------------------------- live log call ---------------------------------
2021-03-26 21:30:02 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
instance_type=Standard_D2s_v4
user_data=None
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-162443-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-162444-image
2021-03-26 21:30:48 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:30:48 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-03-26 21:30:48 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:30:51 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:30:52 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f33599c6eb8>
2021-03-26 21:30:52 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f33599c6eb8>
2021-03-26 21:30:52 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-26 21:30:53 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-26 21:30:53 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:30:53 INFO      integration_testing:clouds.py:181 image serial: 20210325
2021-03-26 21:30:53 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-03-26 21:30:53 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'ls /dev/disk/cloud'
2021-03-26 21:30:53 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'lsblk -pPo NAME,TYPE,MOUNTPOINT'
2021-03-26 21:30:53 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_root-part1'
PASSEDDeleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-162443-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-162444-image

------------------------------ live log teardown -------------------------------
2021-03-26 21:31:34 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-162443-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-162444-image


======================== 2 passed in 412.33s (0:06:52) =========================


=== Focal ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 2 items

tests/integration_tests/bugs/test_lp1901011.py::test_ephemeral[Standard_DS1_v2-True] Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-03-26 21:37:06 INFO      integration_testing:clouds.py:87 Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
2021-03-26 21:37:07 INFO      integration_testing:clouds.py:87 Detected image: image_id=focal os=ubuntu release=focal
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=focal
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-26 21:37:07 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=focal
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for azure
2021-03-26 21:37:07 INFO      integration_testing:conftest.py:156 Setting up environment for azure
Launching instance with launch_kwargs:
user_data=None
image_id=Canonical:0001-com-ubuntu-server-focal-daily:20_04-daily-lts
2021-03-26 21:37:07 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=None
image_id=Canonical:0001-com-ubuntu-server-focal-daily:20_04-daily-lts
2021-03-26 21:38:38 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:38:38 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 13.89.108.63
Retrying SSH connection to ubuntu@13.89.108.63:22 (599s left)
2021-03-26 21:38:39 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 13.89.108.63
Retrying SSH connection to ubuntu@13.89.108.63:22 (598s left)
2021-03-26 21:38:40 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-03-26 21:38:41 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:38:44 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:38:45 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fb2ec3a4908>
2021-03-26 21:38:54 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fb2ec3a4908>
2021-03-26 21:38:54 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.04.1
2021-03-26 21:38:55 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.04.1
2021-03-26 21:38:55 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:38:55 INFO      integration_testing:clouds.py:181 image serial: 20210325
Installing proposed image
2021-03-26 21:38:55 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-26 21:38:55 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-26 21:39:22 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-26 21:39:23 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-26 21:39:23 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:39:24 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:39:24 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:39:25 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:39:25 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo waagent -deprovision+user -force'
Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163706-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163707-image
2021-03-26 21:40:32 INFO      integration_testing:instances.py:113 Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163706-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163707-image
Done with environment setup
2021-03-26 21:41:12 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
user_data=None
instance_type=Standard_DS1_v2
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163706-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163707-image
-------------------------------- live log call ---------------------------------
2021-03-26 21:41:12 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=None
instance_type=Standard_DS1_v2
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163706-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163707-image
2021-03-26 21:42:00 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:42:00 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-03-26 21:42:00 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:42:01 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:42:02 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fb2eb1e1ba8>
2021-03-26 21:42:05 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fb2eb1e1ba8>
2021-03-26 21:42:05 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-26 21:42:06 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-26 21:42:06 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:42:06 INFO      integration_testing:clouds.py:181 image serial: 20210325
2021-03-26 21:42:06 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-03-26 21:42:06 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'ls /dev/disk/cloud'
2021-03-26 21:42:06 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'lsblk -pPo NAME,TYPE,MOUNTPOINT'
2021-03-26 21:42:06 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_root-part1'
2021-03-26 21:42:07 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_resource-part1'
PASSED
tests/integration_tests/bugs/test_lp1901011.py::test_ephemeral[Standard_D2s_v4-False] Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-03-26 21:42:47 INFO      integration_testing:clouds.py:87 Detected image: image_id=focal os=ubuntu release=focal
Launching instance with launch_kwargs:
user_data=None
instance_type=Standard_D2s_v4
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163706-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163707-image
-------------------------------- live log call ---------------------------------
2021-03-26 21:42:47 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=None
instance_type=Standard_D2s_v4
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163706-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163707-image
2021-03-26 21:43:34 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:43:34 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-03-26 21:43:34 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:43:37 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:43:37 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fb2eb1f5ef0>
2021-03-26 21:43:38 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fb2eb1f5ef0>
2021-03-26 21:43:38 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-26 21:43:38 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-26 21:43:38 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:43:38 INFO      integration_testing:clouds.py:181 image serial: 20210325
2021-03-26 21:43:38 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-03-26 21:43:39 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'ls /dev/disk/cloud'
2021-03-26 21:43:39 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'lsblk -pPo NAME,TYPE,MOUNTPOINT'
2021-03-26 21:43:39 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_root-part1'
PASSEDDeleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163706-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163707-image

------------------------------ live log teardown -------------------------------
2021-03-26 21:44:20 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163706-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163707-image


======================== 2 passed in 434.41s (0:07:14) =========================


=== Groovy ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 2 items

tests/integration_tests/bugs/test_lp1901011.py::test_ephemeral[Standard_DS1_v2-True] Detected image: image_id=groovy os=ubuntu release=groovy

-------------------------------- live log setup --------------------------------
2021-03-26 21:49:56 INFO      integration_testing:clouds.py:87 Detected image: image_id=groovy os=ubuntu release=groovy
Detected image: image_id=groovy os=ubuntu release=groovy
2021-03-26 21:49:57 INFO      integration_testing:clouds.py:87 Detected image: image_id=groovy os=ubuntu release=groovy
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=groovy
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-26 21:49:57 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=groovy
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for azure
2021-03-26 21:49:57 INFO      integration_testing:conftest.py:156 Setting up environment for azure
Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-groovy-daily:20_10-daily
user_data=None
2021-03-26 21:49:57 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-groovy-daily:20_10-daily
user_data=None
2021-03-26 21:51:28 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:51:28 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.3p1)
2021-03-26 21:51:29 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:51:30 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:51:31 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f1d975e6c50>
2021-03-26 21:51:36 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f1d975e6c50>
2021-03-26 21:51:36 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.10.1
2021-03-26 21:51:36 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.10.1
2021-03-26 21:51:36 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:51:36 INFO      integration_testing:clouds.py:181 image serial: 20210325
Installing proposed image
2021-03-26 21:51:36 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-26 21:51:36 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-26 21:52:07 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-26 21:52:07 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-26 21:52:07 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:52:08 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:52:08 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:52:09 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:52:09 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo waagent -deprovision+user -force'
Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164956-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164957-image
2021-03-26 21:53:15 INFO      integration_testing:instances.py:113 Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164956-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164957-image
Done with environment setup
2021-03-26 21:53:55 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164956-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164957-image
user_data=None
instance_type=Standard_DS1_v2
-------------------------------- live log call ---------------------------------
2021-03-26 21:53:55 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164956-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164957-image
user_data=None
instance_type=Standard_DS1_v2
2021-03-26 21:54:42 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:54:42 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.3p1)
2021-03-26 21:54:42 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:54:45 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:54:45 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f1d97ac16a0>
2021-03-26 21:54:46 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f1d97ac16a0>
2021-03-26 21:54:46 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-26 21:54:47 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-26 21:54:47 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:54:47 INFO      integration_testing:clouds.py:181 image serial: 20210325
2021-03-26 21:54:47 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-03-26 21:54:47 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'ls /dev/disk/cloud'
2021-03-26 21:54:47 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'lsblk -pPo NAME,TYPE,MOUNTPOINT'
2021-03-26 21:54:47 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_root-part1'
2021-03-26 21:54:47 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_resource-part1'
PASSED
tests/integration_tests/bugs/test_lp1901011.py::test_ephemeral[Standard_D2s_v4-False] Detected image: image_id=groovy os=ubuntu release=groovy

-------------------------------- live log setup --------------------------------
2021-03-26 21:55:28 INFO      integration_testing:clouds.py:87 Detected image: image_id=groovy os=ubuntu release=groovy
Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164956-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164957-image
user_data=None
instance_type=Standard_D2s_v4
-------------------------------- live log call ---------------------------------
2021-03-26 21:55:28 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164956-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164957-image
user_data=None
instance_type=Standard_D2s_v4
2021-03-26 21:56:14 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:56:14 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.3p1)
2021-03-26 21:56:15 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:56:18 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:56:18 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f1d96d24a58>
2021-03-26 21:56:19 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f1d96d24a58>
2021-03-26 21:56:19 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-26 21:56:19 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-26 21:56:19 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:56:20 INFO      integration_testing:clouds.py:181 image serial: 20210325
2021-03-26 21:56:20 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-03-26 21:56:20 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'ls /dev/disk/cloud'
2021-03-26 21:56:20 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'lsblk -pPo NAME,TYPE,MOUNTPOINT'
2021-03-26 21:56:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'realpath /dev/disk/cloud/azure_root-part1'
PASSEDDeleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164956-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164957-image

------------------------------ live log teardown -------------------------------
2021-03-26 21:57:01 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164956-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164957-image


======================== 2 passed in 426.05s (0:07:06) =========================


[Regression Potential]
According to Azure, the Azure host guarantees that the ephemeral resource
disk is attached to the VM before it is booted during VM deployment. If this
remains true, there is no regression potential. Otherwise we could potentially
not configure disks that were previously being configured.
