https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1776958
http://pad.lv/1776958

=== Begin SRU Template ===
[Impact]

Newer LXD versions create a network by default (named `lxdbr0`).  If cloud-init
is configured to create a network named `lxdbr0` itself, it fails because such
a network already exists.  Without this change, users cannot configure `lxdbr0`
to be anything but the default.

[Test Case]

There is an upstream integration test case for this module, which was
introduced(/migrated) to test this bug:
https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/modules/test_lxd_bridge.py

This issue does not present on xenial, whose LXD version predates the initial
network creation; test output is only included for bionic and later.

bionic:

```
bionic installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/2/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@324763289c9a38fc9ac7ec524acb9eb11c7d6c13,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==19.1.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
bionic run-test-pre: PYTHONHASHSEED='1960306729'
bionic run-test: commands[0] | /tmp/integration-tests-tox/bionic/bin/python -m pytest --log-cli-level=INFO modules/test_lxd_bridge.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/bionic/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 3 items

modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxc]
------------------------------------------ live log setup ------------------------------------------
2020-12-15 20:55:23 INFO      integration_testing:clouds.py:73 Detected image: image_id=bionic os=ubuntu release=bionic
2020-12-15 20:55:23 INFO      integration_testing:clouds.py:73 Detected image: image_id=bionic os=ubuntu release=bionic
2020-12-15 20:55:34 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=bionic
PLATFORM=lxd_vm
RUN_UNSTABLE=False
2020-12-15 20:55:34 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_vm
2020-12-15 20:55:34 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:4fca2a9caa531feee10c24a95ea72d28a4e7bb76eec8d0fc0f510926aa8cc8d8
user_data=None
wait=False
2020-12-15 20:57:25 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:57:28 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:57:40 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:57:52 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:58:02 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:58:12 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:58:24 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:58:37 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:58:38 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-15 20:58:39 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-15 20:58:41 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=large-mackerel)
2020-12-15 20:58:41 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-15 20:58:41 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-15 20:58:58 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-15 20:58:59 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~18.04.1
2020-12-15 20:58:59 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-15 20:59:00 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-15 20:59:02 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-15 20:59:03 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-15 20:59:04 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-15 20:59:05 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-15 21:04:11 INFO      integration_testing:instances.py:117 Created new image: local:large-mackerel-snapshot
2020-12-15 21:04:11 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-15 21:04:11 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:large-mackerel-snapshot
user_data=#cloud-config
lxd:
  init:
    storage_backend: dir
  bridge:
    mode: new
    name: lxdbr0
    ipv4_address: 10.100.100.1
    ipv4_netmask: 24
    ipv4_dhcp_first: 10.100.100.100
    ipv4_dhcp_last: 10.100.100.200
    ipv4_nat: true
    domain: lxd

wait=False
2020-12-15 21:05:50 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:05:52 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:06:04 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:06:16 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:06:29 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:06:41 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:06:42 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-15 21:06:44 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-15 21:06:59 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=set-kitten)
------------------------------------------ live log call -------------------------------------------
2020-12-15 21:06:59 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- which lxc
PASSED                                                                                       [ 33%]
modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxd]
------------------------------------------ live log setup ------------------------------------------
2020-12-15 21:07:00 INFO      integration_testing:clouds.py:73 Detected image: image_id=bionic os=ubuntu release=bionic
------------------------------------------ live log call -------------------------------------------
2020-12-15 21:07:00 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- which lxd
PASSED                                                                                       [ 66%]
modules/test_lxd_bridge.py::TestLxdBridge::test_bridge
------------------------------------------ live log setup ------------------------------------------
2020-12-15 21:07:01 INFO      integration_testing:clouds.py:73 Detected image: image_id=bionic os=ubuntu release=bionic
------------------------------------------ live log call -------------------------------------------
2020-12-15 21:07:01 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2020-12-15 21:07:01 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ip addr show lxdbr0'
2020-12-15 21:07:02 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'lxc network show lxdbr0'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-15 21:07:04 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:large-mackerel-snapshot


========================================= warnings summary =========================================
tests/integration_tests/modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxc]
tests/integration_tests/modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxc]
tests/integration_tests/modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxc]
  /tmp/integration-tests-tox/bionic/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================ 3 passed, 3 warnings in 701.48s (0:11:41) =============================
```

focal:

```
focal installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/3/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@324763289c9a38fc9ac7ec524acb9eb11c7d6c13,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==19.1.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
focal run-test-pre: PYTHONHASHSEED='758936835'
focal run-test: commands[0] | /tmp/integration-tests-tox/focal/bin/python -m pytest --log-cli-level=INFO modules/test_lxd_bridge.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/focal/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 3 items

modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxc]
------------------------------------------ live log setup ------------------------------------------
2020-12-15 20:55:30 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
2020-12-15 20:55:30 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
2020-12-15 20:55:42 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=focal
PLATFORM=lxd_vm
RUN_UNSTABLE=False
2020-12-15 20:55:42 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_vm
2020-12-15 20:55:42 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:5f7cb0463720be7bf5c81018f5a1cbeace78e1c38bb2e8fb9a6a545aadc43fe3
user_data=None
wait=False
2020-12-15 20:57:25 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:57:28 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:57:40 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:57:52 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:57:58 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-15 20:58:00 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-15 20:58:04 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=sacred-buffalo)
2020-12-15 20:58:04 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-15 20:58:04 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-15 20:58:23 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-15 20:58:24 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~20.04.1
2020-12-15 20:58:24 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-15 20:58:25 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-15 20:58:26 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-15 20:58:27 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-15 20:58:28 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-15 20:58:29 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-15 21:00:00 INFO      integration_testing:instances.py:117 Created new image: local:sacred-buffalo-snapshot
2020-12-15 21:00:01 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-15 21:00:01 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:sacred-buffalo-snapshot
user_data=#cloud-config
lxd:
  init:
    storage_backend: dir
  bridge:
    mode: new
    name: lxdbr0
    ipv4_address: 10.100.100.1
    ipv4_netmask: 24
    ipv4_dhcp_first: 10.100.100.100
    ipv4_dhcp_last: 10.100.100.200
    ipv4_nat: true
    domain: lxd

wait=False
2020-12-15 21:01:47 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:01:49 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:02:01 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:02:13 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:02:22 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-15 21:02:25 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-15 21:02:37 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=credible-polliwog)
------------------------------------------ live log call -------------------------------------------
2020-12-15 21:02:37 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- which lxc
PASSED                                                                                       [ 33%]
modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxd]
------------------------------------------ live log setup ------------------------------------------
2020-12-15 21:02:38 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
------------------------------------------ live log call -------------------------------------------
2020-12-15 21:02:38 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- which lxd
PASSED                                                                                       [ 66%]
modules/test_lxd_bridge.py::TestLxdBridge::test_bridge
------------------------------------------ live log setup ------------------------------------------
2020-12-15 21:02:40 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
------------------------------------------ live log call -------------------------------------------
2020-12-15 21:02:40 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2020-12-15 21:02:41 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ip addr show lxdbr0'
2020-12-15 21:02:42 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'lxc network show lxdbr0'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-15 21:02:44 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:sacred-buffalo-snapshot


========================================= warnings summary =========================================
tests/integration_tests/modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxc]
tests/integration_tests/modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxc]
  /tmp/integration-tests-tox/focal/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================ 3 passed, 2 warnings in 433.82s (0:07:13) =============================
```

groovy:

```
groovy installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/4/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@d1c63026c76ed3ef02dc21982f9f7eeea2606f2a,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==20.0.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
groovy run-test-pre: PYTHONHASHSEED='1011297671'
groovy run-test: commands[0] | /tmp/integration-tests-tox/groovy/bin/python -m pytest --log-cli-level=INFO modules/test_lxd_bridge.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/groovy/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 3 items

modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxc]
------------------------------------------ live log setup ------------------------------------------
2020-12-15 20:55:36 INFO      integration_testing:clouds.py:73 Detected image: image_id=groovy os=ubuntu release=groovy
2020-12-15 20:55:36 INFO      integration_testing:clouds.py:73 Detected image: image_id=groovy os=ubuntu release=groovy
2020-12-15 20:55:47 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=groovy
PLATFORM=lxd_vm
RUN_UNSTABLE=False
2020-12-15 20:55:47 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_vm
2020-12-15 20:55:47 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:b43f7b486a7c27a833c644b51e4995d7de4c9c398d3fa930229b0b271da4ef0f
user_data=None
wait=False
2020-12-15 20:57:25 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:57:28 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:57:40 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:57:52 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:58:03 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 20:58:04 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-15 20:58:06 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-15 20:58:07 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=coherent-raven)
2020-12-15 20:58:07 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-15 20:58:07 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-15 20:58:27 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-15 20:58:28 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~20.10.1
2020-12-15 20:58:28 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-15 20:58:29 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-15 20:58:30 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-15 20:58:31 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-15 20:58:32 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-15 20:58:33 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-15 21:02:09 INFO      integration_testing:instances.py:117 Created new image: local:coherent-raven-snapshot
2020-12-15 21:02:10 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-15 21:02:10 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:coherent-raven-snapshot
user_data=#cloud-config
lxd:
  init:
    storage_backend: dir
  bridge:
    mode: new
    name: lxdbr0
    ipv4_address: 10.100.100.1
    ipv4_netmask: 24
    ipv4_dhcp_first: 10.100.100.100
    ipv4_dhcp_last: 10.100.100.200
    ipv4_nat: true
    domain: lxd

wait=False
2020-12-15 21:04:00 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:04:03 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:04:15 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:04:27 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:04:37 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-15 21:04:38 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-15 21:04:40 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-15 21:04:50 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=flowing-parrot)
------------------------------------------ live log call -------------------------------------------
2020-12-15 21:04:50 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- which lxc
PASSED                                                                                       [ 33%]
modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxd]
------------------------------------------ live log setup ------------------------------------------
2020-12-15 21:04:51 INFO      integration_testing:clouds.py:73 Detected image: image_id=groovy os=ubuntu release=groovy
------------------------------------------ live log call -------------------------------------------
2020-12-15 21:04:51 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- which lxd
PASSED                                                                                       [ 66%]
modules/test_lxd_bridge.py::TestLxdBridge::test_bridge
------------------------------------------ live log setup ------------------------------------------
2020-12-15 21:04:52 INFO      integration_testing:clouds.py:73 Detected image: image_id=groovy os=ubuntu release=groovy
------------------------------------------ live log call -------------------------------------------
2020-12-15 21:04:52 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2020-12-15 21:04:53 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ip addr show lxdbr0'
2020-12-15 21:04:54 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'lxc network show lxdbr0'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-15 21:04:56 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:coherent-raven-snapshot


========================================= warnings summary =========================================
tests/integration_tests/modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxc]
tests/integration_tests/modules/test_lxd_bridge.py::TestLxdBridge::test_binaries_installed[lxc]
  /tmp/integration-tests-tox/groovy/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================ 3 passed, 2 warnings in 559.86s (0:09:19) =============================
```

[Regression Potential]

This change will only affect newly-provisioned instances which have LXD network
creation configuration passed to them.  Such users will see their configuration
successfully applied where previously it would have failed.
