https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1900837
http://pad.lv/1900837

=== Begin SRU Template ===
[Impact]

cloud-init would force its log file to be world-readable on every boot.  This
presents an issue for those who have modified its permissions: they would
expect them to be retained.

In terms of this specific report: this causes CIS auditing to fail on
cloud-init enabled systems.

[Test Case]

There is an upstream integration test for this bug:
https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/bugs/test_lp1900837.py

xenial:

```
GLOB sdist-make: /home/daniel/dev/cloud-init/setup.py
xenial inst-nodeps: /tmp/integration-tests-tox/.tmp/package/2/cloud-init-20.4.zip
xenial installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/2/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@324763289c9a38fc9ac7ec524acb9eb11c7d6c13,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==20.0.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
xenial run-test-pre: PYTHONHASHSEED='1792268271'
xenial run-test: commands[0] | /tmp/integration-tests-tox/xenial/bin/python -m pytest --log-cli-level=INFO bugs/test_lp1900837.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/xenial/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item

bugs/test_lp1900837.py::TestLogPermissionsNotResetOnReboot::test_permissions_unchanged
------------------------------------------ live log setup ------------------------------------------
2020-12-10 20:35:07 INFO      integration_testing:clouds.py:73 Detected image: image_id=xenial os=ubuntu release=xenial
2020-12-10 20:35:07 INFO      integration_testing:clouds.py:73 Detected image: image_id=xenial os=ubuntu release=xenial
2020-12-10 20:35:18 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=xenial
PLATFORM=lxd_container
RUN_UNSTABLE=False
2020-12-10 20:35:18 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_container
2020-12-10 20:35:18 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:0f411e79e10761ad7aa433a4965fbc2fef18a47879a9c4ff0408884d41e2bb54
user_data=None
wait=False
2020-12-10 20:35:26 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:35:27 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:35:37 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:35:37 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:35:38 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:35:38 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=glorious-cicada)
2020-12-10 20:35:38 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-10 20:35:38 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-10 20:36:02 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-10 20:36:02 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~16.04.1
2020-12-10 20:36:02 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:36:03 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:36:03 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:36:03 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:36:03 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:36:04 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:38:01 INFO      integration_testing:instances.py:117 Created new image: local:glorious-cicada-snapshot
2020-12-10 20:38:02 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-10 20:38:02 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:glorious-cicada-snapshot
user_data=None
wait=False
2020-12-10 20:38:17 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:38:18 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:38:18 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:38:20 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=quality-moth)
------------------------------------------ live log call -------------------------------------------
2020-12-10 20:38:20 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
2020-12-10 20:38:21 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'chmod 600 /var/log/cloud-init.log'
2020-12-10 20:38:21 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
2020-12-10 20:38:24 INFO      integration_testing:instances.py:67 Instance restarted; waiting for boot
2020-12-10 20:38:24 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:38:24 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:38:25 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:38:27 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-10 20:38:29 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:glorious-cicada-snapshot


========================================= warnings summary =========================================
tests/integration_tests/bugs/test_lp1900837.py::TestLogPermissionsNotResetOnReboot::test_permissions_unchanged
  /tmp/integration-tests-tox/xenial/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= 1 passed, 1 warning in 201.69s (0:03:21) =============================
```

bionic:

```
GLOB sdist-make: /home/daniel/dev/cloud-init/setup.py
bionic inst-nodeps: /tmp/integration-tests-tox/.tmp/package/1/cloud-init-20.4.zip
bionic installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/1/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@324763289c9a38fc9ac7ec524acb9eb11c7d6c13,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==19.1.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
bionic run-test-pre: PYTHONHASHSEED='378096409'
bionic run-test: commands[0] | /tmp/integration-tests-tox/bionic/bin/python -m pytest --log-cli-level=INFO bugs/test_lp1900837.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/bionic/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item

bugs/test_lp1900837.py::TestLogPermissionsNotResetOnReboot::test_permissions_unchanged
------------------------------------------ live log setup ------------------------------------------
2020-12-10 20:34:56 INFO      integration_testing:clouds.py:73 Detected image: image_id=bionic os=ubuntu release=bionic
2020-12-10 20:34:56 INFO      integration_testing:clouds.py:73 Detected image: image_id=bionic os=ubuntu release=bionic
2020-12-10 20:35:07 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=bionic
PLATFORM=lxd_container
RUN_UNSTABLE=False
2020-12-10 20:35:07 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_container
2020-12-10 20:35:07 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:0cb978a481d837eae60e40250faee5cbbff7d5325cac859fbd6222ebee0f1896
user_data=None
wait=False
2020-12-10 20:35:13 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:35:14 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:35:24 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:35:25 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:35:26 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:35:27 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=light-squid)
2020-12-10 20:35:27 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-10 20:35:27 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-10 20:36:02 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-10 20:36:03 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~18.04.1
2020-12-10 20:36:03 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:36:03 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:36:03 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:36:04 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:36:04 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:36:05 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:36:53 INFO      integration_testing:instances.py:117 Created new image: local:light-squid-snapshot
2020-12-10 20:36:53 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-10 20:36:53 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:light-squid-snapshot
user_data=None
wait=False
2020-12-10 20:37:28 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:37:28 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:37:29 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:37:37 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=civil-marten)
------------------------------------------ live log call -------------------------------------------
2020-12-10 20:37:37 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
2020-12-10 20:37:37 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'chmod 600 /var/log/cloud-init.log'
2020-12-10 20:37:37 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
2020-12-10 20:37:40 INFO      integration_testing:instances.py:67 Instance restarted; waiting for boot
2020-12-10 20:37:40 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:37:40 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:37:41 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:37:44 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-10 20:37:47 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:light-squid-snapshot


========================================= warnings summary =========================================
tests/integration_tests/bugs/test_lp1900837.py::TestLogPermissionsNotResetOnReboot::test_permissions_unchanged
  /tmp/integration-tests-tox/bionic/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= 1 passed, 1 warning in 170.97s (0:02:50) =============================
```

focal:

```
GLOB sdist-make: /home/daniel/dev/cloud-init/setup.py
focal inst-nodeps: /tmp/integration-tests-tox/.tmp/package/3/cloud-init-20.4.zip
focal installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/3/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@324763289c9a38fc9ac7ec524acb9eb11c7d6c13,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==19.1.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
focal run-test-pre: PYTHONHASHSEED='545509093'
focal run-test: commands[0] | /tmp/integration-tests-tox/focal/bin/python -m pytest --log-cli-level=INFO bugs/test_lp1900837.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/focal/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item

bugs/test_lp1900837.py::TestLogPermissionsNotResetOnReboot::test_permissions_unchanged
------------------------------------------ live log setup ------------------------------------------
2020-12-10 20:35:27 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
2020-12-10 20:35:27 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
2020-12-10 20:35:38 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=focal
PLATFORM=lxd_container
RUN_UNSTABLE=False
2020-12-10 20:35:38 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_container
2020-12-10 20:35:38 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:3e9403fe7645000fc49ec89bca056c7fd53e9a142a3a9054ee02c13a2f14b6d0
user_data=None
wait=False
2020-12-10 20:35:59 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:36:00 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:36:10 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:36:10 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:36:11 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:36:26 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=enabling-parrot)
2020-12-10 20:36:26 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-10 20:36:26 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-10 20:36:48 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-10 20:36:48 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~20.04.1
2020-12-10 20:36:48 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:36:49 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:36:49 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:36:50 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:36:50 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:36:50 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:38:57 INFO      integration_testing:instances.py:117 Created new image: local:enabling-parrot-snapshot
2020-12-10 20:38:58 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-10 20:38:58 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:enabling-parrot-snapshot
user_data=None
wait=False
2020-12-10 20:39:12 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:39:12 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:39:13 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:39:22 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=splendid-sailfish)
------------------------------------------ live log call -------------------------------------------
2020-12-10 20:39:22 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
2020-12-10 20:39:24 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'chmod 600 /var/log/cloud-init.log'
2020-12-10 20:39:28 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
2020-12-10 20:39:30 INFO      integration_testing:instances.py:67 Instance restarted; waiting for boot
2020-12-10 20:39:30 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:39:30 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:39:31 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:39:33 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-10 20:39:36 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:enabling-parrot-snapshot


========================================= warnings summary =========================================
tests/integration_tests/bugs/test_lp1900837.py::TestLogPermissionsNotResetOnReboot::test_permissions_unchanged
  /tmp/integration-tests-tox/focal/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= 1 passed, 1 warning in 249.20s (0:04:09) =============================
```

groovy:

```
GLOB sdist-make: /home/daniel/dev/cloud-init/setup.py
groovy inst-nodeps: /tmp/integration-tests-tox/.tmp/package/4/cloud-init-20.4.zip
groovy installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/4/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@d1c63026c76ed3ef02dc21982f9f7eeea2606f2a,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==20.0.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
groovy run-test-pre: PYTHONHASHSEED='655234533'
groovy run-test: commands[0] | /tmp/integration-tests-tox/groovy/bin/python -m pytest --log-cli-level=INFO bugs/test_lp1900837.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/groovy/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item

bugs/test_lp1900837.py::TestLogPermissionsNotResetOnReboot::test_permissions_unchanged
------------------------------------------ live log setup ------------------------------------------
2020-12-10 20:35:35 INFO      integration_testing:clouds.py:73 Detected image: image_id=groovy os=ubuntu release=groovy
2020-12-10 20:35:35 INFO      integration_testing:clouds.py:73 Detected image: image_id=groovy os=ubuntu release=groovy
2020-12-10 20:35:46 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=groovy
PLATFORM=lxd_container
RUN_UNSTABLE=False
2020-12-10 20:35:46 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_container
2020-12-10 20:35:46 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:bac1692e9ec7f5c5cee35d149ca789121bed238c1182df2134b5aefa3977f3e0
user_data=None
wait=False
2020-12-10 20:37:16 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:37:16 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:37:26 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:37:27 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:37:27 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:37:35 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=great-chow)
2020-12-10 20:37:35 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-10 20:37:35 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-10 20:37:51 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-10 20:37:52 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~20.10.1
2020-12-10 20:37:52 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:37:53 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:37:53 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:37:53 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:37:53 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 20:37:54 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 20:39:58 INFO      integration_testing:instances.py:117 Created new image: local:great-chow-snapshot
2020-12-10 20:40:00 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-10 20:40:00 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:great-chow-snapshot
user_data=None
wait=False
2020-12-10 20:40:12 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:40:13 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:40:13 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:40:20 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=well-lionfish)
------------------------------------------ live log call -------------------------------------------
2020-12-10 20:40:20 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
2020-12-10 20:40:21 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'chmod 600 /var/log/cloud-init.log'
2020-12-10 20:40:21 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
2020-12-10 20:40:23 INFO      integration_testing:instances.py:67 Instance restarted; waiting for boot
2020-12-10 20:40:23 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 20:40:23 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 20:40:24 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 20:40:29 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'stat -c %a /var/log/cloud-init.log'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-10 20:40:31 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:great-chow-snapshot


========================================= warnings summary =========================================
tests/integration_tests/bugs/test_lp1900837.py::TestLogPermissionsNotResetOnReboot::test_permissions_unchanged
  /tmp/integration-tests-tox/groovy/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= 1 passed, 1 warning in 295.82s (0:04:55) =============================
```

[Regression Potential]

This is a small change to a utility function in cloud-init; its default
behaviour remains the same.  The only functional change is that cloud-init will
no longer reset the permissions of /var/log/cloud-init.log to 644 on every
boot.
