============================= test session starts ==============================
platform linux -- Python 3.6.10, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 6 items

tests/integration_tests/modules/test_seed_random_data.py::TestSeedRandomData::test_seed_random_data Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-11-09 15:30:07 INFO      integration_testing:clouds.py:91 Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
2021-11-09 15:30:20 INFO      integration_testing:clouds.py:91 Detected image: image_id=focal os=ubuntu release=focal
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=focal
PLATFORM=gce
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-11-09 15:30:27 INFO      integration_testing:clouds.py:132 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=focal
PLATFORM=gce
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for gce
2021-11-09 15:30:27 INFO      integration_testing:conftest.py:156 Setting up environment for gce
Launching instance with launch_kwargs:
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2004-focal-v20211108
user_data=None
2021-11-09 15:30:27 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2004-focal-v20211108
user_data=None
2021-11-09 15:30:38 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:30:54 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:30:55 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:30:56 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:30:58 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:30:59 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:31:00 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:31:01 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:31:02 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:31:03 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:31:04 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:31:05 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:31:06 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:31:07 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:31:09 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:31:10 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:31:10 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-09 15:31:10 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 15:31:14 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 15:31:14 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:31:15 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:31:17 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:31:17 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=2060428422213479164)
2021-11-09 15:31:17 INFO      integration_testing:clouds.py:176 Launched instance: GceInstance(instance_id=2060428422213479164)
2021-11-09 15:31:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.4
2021-11-09 15:31:18 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.4
2021-11-09 15:31:18 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211108
2021-11-09 15:31:18 INFO      integration_testing:clouds.py:186 image serial: 20211108
Installing proposed image
2021-11-09 15:31:18 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:31:18 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:31:18 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-11-09 15:31:29 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-11-09 15:31:36 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.4-0ubuntu1~20.04.1
2021-11-09 15:31:37 INFO      integration_testing:instances.py:139 Installed cloud-init version: 21.4-0ubuntu1~20.04.1
2021-11-09 15:31:37 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-09 15:31:38 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-093007-image
2021-11-09 15:32:28 INFO      integration_testing:instances.py:116 Created new image: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-093007-image
Done with environment setup
2021-11-09 15:32:29 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-093007-image
user_data=#cloud-config
random_seed:
  data: 'MYUb34023nD:LFDK10913jk;dfnk:Df'
  encoding: raw
  file: /root/seed

2021-11-09 15:32:29 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-093007-image
user_data=#cloud-config
random_seed:
  data: 'MYUb34023nD:LFDK10913jk;dfnk:Df'
  encoding: raw
  file: /root/seed

2021-11-09 15:32:50 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:33:07 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:33:08 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:33:09 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:33:10 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:33:11 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:33:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:33:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:33:13 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-09 15:33:14 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 15:33:18 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 15:33:18 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:33:19 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:33:20 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:33:21 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:33:23 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:33:23 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=1585514999028591202)
2021-11-09 15:33:24 INFO      integration_testing:clouds.py:176 Launched instance: GceInstance(instance_id=1585514999028591202)
2021-11-09 15:33:24 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-09 15:33:24 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-09 15:33:24 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211108
2021-11-09 15:33:24 INFO      integration_testing:clouds.py:186 image serial: 20211108
-------------------------------- live log call ---------------------------------
2021-11-09 15:33:24 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'head -c 31 < /root/seed'
PASSED
tests/integration_tests/modules/test_ssh_generate.py::TestSshKeysGenerate::test_ssh_keys_generated[/etc/ssh/ssh_host_ecdsa_key.pub] Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-11-09 15:33:43 INFO      integration_testing:clouds.py:91 Detected image: image_id=focal os=ubuntu release=focal
Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-093007-image
user_data=#cloud-config
ssh_genkeytypes:
  - ecdsa
  - ed25519
authkey_hash: sha512

2021-11-09 15:33:43 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-093007-image
user_data=#cloud-config
ssh_genkeytypes:
  - ecdsa
  - ed25519
authkey_hash: sha512

2021-11-09 15:33:55 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:34:11 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:34:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:34:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:34:14 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:34:15 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:34:17 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:34:18 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:34:18 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-09 15:34:19 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 15:34:21 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 15:34:21 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:34:22 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:34:23 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:34:25 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:34:26 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:34:26 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=4457752392291002935)
2021-11-09 15:34:27 INFO      integration_testing:clouds.py:176 Launched instance: GceInstance(instance_id=4457752392291002935)
2021-11-09 15:34:27 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-09 15:34:27 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-09 15:34:27 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211108
2021-11-09 15:34:28 INFO      integration_testing:clouds.py:186 image serial: 20211108
-------------------------------- live log call ---------------------------------
2021-11-09 15:34:28 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/ssh/ssh_host_ecdsa_key.pub'
PASSED
tests/integration_tests/modules/test_ssh_generate.py::TestSshKeysGenerate::test_ssh_keys_generated[/etc/ssh/ssh_host_ecdsa_key] Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-11-09 15:34:28 INFO      integration_testing:clouds.py:91 Detected image: image_id=focal os=ubuntu release=focal
-------------------------------- live log call ---------------------------------
2021-11-09 15:34:28 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/ssh/ssh_host_ecdsa_key'
PASSED
tests/integration_tests/modules/test_ssh_generate.py::TestSshKeysGenerate::test_ssh_keys_generated[/etc/ssh/ssh_host_ed25519_key.pub] Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-11-09 15:34:28 INFO      integration_testing:clouds.py:91 Detected image: image_id=focal os=ubuntu release=focal
-------------------------------- live log call ---------------------------------
2021-11-09 15:34:28 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/ssh/ssh_host_ed25519_key.pub'
PASSED
tests/integration_tests/modules/test_ssh_generate.py::TestSshKeysGenerate::test_ssh_keys_generated[/etc/ssh/ssh_host_ed25519_key] Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-11-09 15:34:28 INFO      integration_testing:clouds.py:91 Detected image: image_id=focal os=ubuntu release=focal
-------------------------------- live log call ---------------------------------
2021-11-09 15:34:28 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/ssh/ssh_host_ed25519_key'
PASSED
tests/integration_tests/modules/test_user_events.py::test_boot_event_disabled_by_default Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-11-09 15:35:17 INFO      integration_testing:clouds.py:91 Detected image: image_id=focal os=ubuntu release=focal
Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-093007-image
user_data=None
2021-11-09 15:35:17 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-093007-image
user_data=None
2021-11-09 15:35:28 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:36:00 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-09 15:36:00 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 15:36:02 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 15:36:02 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:36:03 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=2841804366311533529)
2021-11-09 15:36:03 INFO      integration_testing:clouds.py:176 Launched instance: GceInstance(instance_id=2841804366311533529)
2021-11-09 15:36:03 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-09 15:36:04 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-09 15:36:04 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211108
2021-11-09 15:36:04 INFO      integration_testing:clouds.py:186 image serial: 20211108
-------------------------------- live log call ---------------------------------
2021-11-09 15:36:04 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-09 15:36:05 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ls /sys/class/net'
2021-11-09 15:36:05 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-11-09 15:36:05 INFO      paramiko.transport.sftp:sftp.py:158 [chan 9] Opened sftp connection (server version 3)
2021-11-09 15:36:06 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'mv /var/tmp/6f1a4a4a-b31d-49c3-9264-11b86a2f476f.tmp /etc/netplan/50-cloud-init.yaml'
2021-11-09 15:36:06 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'rm /var/log/cloud-init.log'
Restarting instance and waiting for boot
2021-11-09 15:36:06 INFO      integration_testing:instances.py:68 Restarting instance and waiting for boot
2021-11-09 15:37:05 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:37:21 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:37:22 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:37:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:37:25 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:37:26 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:37:27 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:37:28 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:37:28 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-09 15:37:29 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 15:37:30 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 15:37:31 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:37:31 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
2021-11-09 15:37:31 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
SKIPPED (Test only valid for existing instances)Deleting snapshot image created for this testrun: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-093007-image

------------------------------ live log teardown -------------------------------
2021-11-09 15:38:19 INFO      integration_testing:clouds.py:207 Deleting snapshot image created for this testrun: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-093007-image


=============================== warnings summary ===============================
../envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
    _pytest.deprecated.STRICT_OPTION, stacklevel=2

conftest.py:68
  /home/james/cloud-init/conftest.py:68: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(autouse=True)

conftest.py:168
  /home/james/cloud-init/conftest.py:168: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:104
  /home/james/cloud-init/tests/integration_tests/conftest.py:104: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='session')

tests/integration_tests/conftest.py:261
  /home/james/cloud-init/tests/integration_tests/conftest.py:261: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:268
  /home/james/cloud-init/tests/integration_tests/conftest.py:268: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='module')

tests/integration_tests/conftest.py:275
  /home/james/cloud-init/tests/integration_tests/conftest.py:275: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='class')

tests/integration_tests/modules/test_seed_random_data.py::TestSeedRandomData::test_seed_random_data
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/simplestreams/mirrors/__init__.py:207: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self.prefix, path)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============= 5 passed, 1 skipped, 8 warnings in 493.74s (0:08:13) =============
