=================================================================================================================================== test session starts ====================================================================================================================================
platform linux -- Python 3.5.10, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, configfile: tox.ini
plugins: cov-2.11.1
collected 2 items

tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_explicit_password_set_correctly Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------------------------------------------
2021-09-11 04:05:42 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
2021-09-11 04:05:42 INFO      botocore.credentials:credentials.py:1217 Found credentials in shared credentials file: ~/.aws/credentials
Detected image: image_id=hirsute os=ubuntu release=hirsute
2021-09-11 04:05:42 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=hirsute
PLATFORM=ec2
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-09-11 04:05:50 INFO      integration_testing:clouds.py:129 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=hirsute
PLATFORM=ec2
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for ec2
2021-09-11 04:05:50 INFO      integration_testing:conftest.py:156 Setting up environment for ec2
Launching instance with launch_kwargs:
image_id=ami-01e80d9e7b6daabcf
user_data=None
2021-09-11 04:05:50 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=ami-01e80d9e7b6daabcf
user_data=None
2021-09-11 04:06:21 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-11 04:06:25 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-11 04:06:27 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-11 04:06:28 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-11 04:06:29 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-11 04:06:29 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-09-11 04:06:30 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-11 04:06:33 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f01aee6d9b0>, instance=ec2.Instance(id='i-0743e928bb86f3ad2'))
2021-09-11 04:06:41 INFO      integration_testing:clouds.py:173 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f01aee6d9b0>, instance=ec2.Instance(id='i-0743e928bb86f3ad2'))
2021-09-11 04:06:41 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~21.04.1
2021-09-11 04:06:41 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~21.04.1
2021-09-11 04:06:41 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210908
2021-09-11 04:06:41 INFO      integration_testing:clouds.py:183 image serial: 20210908
Installing proposed image
2021-09-11 04:06:41 INFO      integration_testing:instances.py:150 Installing proposed image
2021-09-11 04:06:41 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-09-11 04:06:42 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-09-11 04:06:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-09-11 04:07:04 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-11 04:07:05 INFO      integration_testing:instances.py:137 Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-11 04:07:05 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-11 04:07:05 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-09-11 04:07:05 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-11 04:07:06 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-09-11 04:09:24 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-11 04:09:40 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-09-11 04:09:40 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-11 04:09:42 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Created new image: ami-02823131ce7dd85ec
2021-09-11 04:09:44 INFO      integration_testing:instances.py:114 Created new image: ami-02823131ce7dd85ec
Done with environment setup
2021-09-11 04:10:29 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=ami-02823131ce7dd85ec
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
  list:
    - tom:mypassword123!
    - dick:RANDOM
    - harry:RANDOM
    - mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-11 04:10:29 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=ami-02823131ce7dd85ec
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
  list:
    - tom:mypassword123!
    - dick:RANDOM
    - harry:RANDOM
    - mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-11 04:11:01 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-11 04:11:17 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-09-11 04:11:17 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-11 04:11:20 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f01aee6d9b0>, instance=ec2.Instance(id='i-09e9086bcd3c24d2c'))
2021-09-11 04:11:22 INFO      integration_testing:clouds.py:173 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f01aee6d9b0>, instance=ec2.Instance(id='i-09e9086bcd3c24d2c'))
2021-09-11 04:11:22 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-11 04:11:23 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-11 04:11:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210908
2021-09-11 04:11:23 INFO      integration_testing:clouds.py:183 image serial: 20210908
-------------------------------------------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------------------------------------------
2021-09-11 04:11:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_explicit_password_set_correctly Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------------------------------------------
2021-09-11 04:11:54 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
Launching instance with launch_kwargs:
image_id=ami-02823131ce7dd85ec
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
    list: |
      tom:mypassword123!
      dick:RANDOM
      harry:RANDOM
      mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-11 04:11:54 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=ami-02823131ce7dd85ec
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
    list: |
      tom:mypassword123!
      dick:RANDOM
      harry:RANDOM
      mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-11 04:12:40 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-11 04:12:41 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-09-11 04:12:41 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-11 04:12:43 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f01aee6d9b0>, instance=ec2.Instance(id='i-0936aa4ad9b218648'))
2021-09-11 04:12:48 INFO      integration_testing:clouds.py:173 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f01aee6d9b0>, instance=ec2.Instance(id='i-0936aa4ad9b218648'))
2021-09-11 04:12:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-11 04:12:48 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-11 04:12:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210908
2021-09-11 04:12:48 INFO      integration_testing:clouds.py:183 image serial: 20210908
-------------------------------------------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------------------------------------------
2021-09-11 04:12:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSEDDeleting snapshot image created for this testrun: ami-02823131ce7dd85ec

------------------------------------------------------------------------------------------------------------------------------------ live log teardown -------------------------------------------------------------------------------------------------------------------------------------
2021-09-11 04:13:34 INFO      integration_testing:clouds.py:204 Deleting snapshot image created for this testrun: ami-02823131ce7dd85ec


===================================================================================================================================== warnings summary =====================================================================================================================================
../envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8
  /home/james/envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
    from cryptography.hazmat.primitives.asymmetric.utils import (

tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_explicit_password_set_correctly
  /home/james/envs/cloud-init/lib/python3.5/site-packages/simplestreams/mirrors/__init__.py:207: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self.prefix, path)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================================================================== 2 passed, 2 warnings in 472.57s (0:07:52) =========================================================================================================================
