================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.5.10, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, configfile: tox.ini
plugins: cov-2.11.1
collected 18 items

tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_no_duplicate_users_in_shadow Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:36:15 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
2021-09-10 04:36:15 INFO      botocore.credentials:credentials.py:1217 Found credentials in shared credentials file: ~/.aws/credentials
Detected image: image_id=bionic os=ubuntu release=bionic
2021-09-10 04:36:15 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=bionic
PLATFORM=ec2
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-09-10 04:36:21 INFO      integration_testing:clouds.py:129 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=bionic
PLATFORM=ec2
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for ec2
2021-09-10 04:36:21 INFO      integration_testing:conftest.py:156 Setting up environment for ec2
Launching instance with launch_kwargs:
image_id=ami-08853a6c93b952e8b
user_data=None
2021-09-10 04:36:21 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=ami-08853a6c93b952e8b
user_data=None
2021-09-10 04:36:53 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:10 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:11 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:14 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:15 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:16 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:18 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:19 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:20 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:21 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:22 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:24 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:26 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:27 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:37:27 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-09-10 04:37:27 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-10 04:37:42 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f11533c2208>, instance=ec2.Instance(id='i-0ef7a1c104f2c0e8e'))
2021-09-10 04:39:40 INFO      integration_testing:clouds.py:173 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f11533c2208>, instance=ec2.Instance(id='i-0ef7a1c104f2c0e8e'))
2021-09-10 04:39:40 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~18.04.1
2021-09-10 04:39:45 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~18.04.1
2021-09-10 04:39:45 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210907
2021-09-10 04:39:45 INFO      integration_testing:clouds.py:183 image serial: 20210907
Installing proposed image
2021-09-10 04:39:45 INFO      integration_testing:instances.py:150 Installing proposed image
2021-09-10 04:39:45 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-09-10 04:39:46 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-09-10 04:40:12 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-09-10 04:40:20 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~18.04.2
2021-09-10 04:40:21 INFO      integration_testing:instances.py:137 Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~18.04.2
2021-09-10 04:40:21 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-10 04:40:22 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-09-10 04:40:22 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-10 04:40:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-09-10 04:43:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:28 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:29 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:31 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:32 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:33 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:34 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:35 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:36 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:37 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:38 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:40 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:41 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:42 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:43 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:44 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:43:45 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-09-10 04:43:46 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-10 04:43:56 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Created new image: ami-079794d1571d5b7dc
2021-09-10 04:44:41 INFO      integration_testing:instances.py:114 Created new image: ami-079794d1571d5b7dc
Done with environment setup
2021-09-10 04:45:26 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=ami-079794d1571d5b7dc
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
  list:
    - tom:mypassword123!
    - dick:RANDOM
    - harry:RANDOM
    - mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-10 04:45:26 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=ami-079794d1571d5b7dc
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
  list:
    - tom:mypassword123!
    - dick:RANDOM
    - harry:RANDOM
    - mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-10 04:45:58 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:07 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:08 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:09 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:10 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:11 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:14 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:16 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:17 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:18 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:19 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:20 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:21 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:22 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:46:24 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-09-10 04:46:26 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-10 04:46:36 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f11533c2208>, instance=ec2.Instance(id='i-08e420e3b8c2d56d8'))
2021-09-10 04:47:24 INFO      integration_testing:clouds.py:173 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f11533c2208>, instance=ec2.Instance(id='i-08e420e3b8c2d56d8'))
2021-09-10 04:47:24 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~18.04.2
2021-09-10 04:47:29 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~18.04.2
2021-09-10 04:47:29 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210907
2021-09-10 04:47:29 INFO      integration_testing:clouds.py:183 image serial: 20210907
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:47:29 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_password_in_users_dict_set_correctly Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:47:29 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:47:29 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_password_in_chpasswd_list_set_correctly Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:47:29 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:47:29 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_random_passwords_set_correctly Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:47:30 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:47:30 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_random_passwords_not_stored_in_cloud_init_output_log Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:47:30 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:47:30 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init-output.log'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_random_passwords_emitted_to_serial_console Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:47:30 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_explicit_password_set_correctly Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:50:09 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:50:09 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_shadow_expected_users Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:50:09 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:50:09 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_sshd_config Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:50:09 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:50:09 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/ssh/sshd_config'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_no_duplicate_users_in_shadow Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:50:40 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
Launching instance with launch_kwargs:
image_id=ami-079794d1571d5b7dc
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
    list: |
      tom:mypassword123!
      dick:RANDOM
      harry:RANDOM
      mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-10 04:50:40 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=ami-079794d1571d5b7dc
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
    list: |
      tom:mypassword123!
      dick:RANDOM
      harry:RANDOM
      mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-10 04:51:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:51:28 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:51:29 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:51:30 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:51:32 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:51:33 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:51:34 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:51:35 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:51:36 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:51:37 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 04:51:38 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-09-10 04:51:39 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-10 04:51:48 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f11533c2208>, instance=ec2.Instance(id='i-0461aa35941a77e3a'))
2021-09-10 04:52:38 INFO      integration_testing:clouds.py:173 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f11533c2208>, instance=ec2.Instance(id='i-0461aa35941a77e3a'))
2021-09-10 04:52:38 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~18.04.2
2021-09-10 04:52:43 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~18.04.2
2021-09-10 04:52:43 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210907
2021-09-10 04:52:43 INFO      integration_testing:clouds.py:183 image serial: 20210907
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:52:43 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_password_in_users_dict_set_correctly Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:52:43 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:52:43 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_password_in_chpasswd_list_set_correctly Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:52:44 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:52:44 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_random_passwords_set_correctly Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:52:44 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:52:44 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_random_passwords_not_stored_in_cloud_init_output_log Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:52:44 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:52:44 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init-output.log'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_random_passwords_emitted_to_serial_console Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:52:44 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_explicit_password_set_correctly Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:55:24 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:55:24 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_shadow_expected_users Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:55:24 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:55:24 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_sshd_config Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 04:55:24 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
--------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
2021-09-10 04:55:24 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/ssh/sshd_config'
PASSEDDeleting snapshot image created for this testrun: ami-079794d1571d5b7dc

------------------------------------------------------------------------------------------------- live log teardown -------------------------------------------------------------------------------------------------
2021-09-10 04:56:10 INFO      integration_testing:clouds.py:204 Deleting snapshot image created for this testrun: ami-079794d1571d5b7dc


================================================================================================= warnings summary ==================================================================================================
../envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8
  /home/james/envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
    from cryptography.hazmat.primitives.asymmetric.utils import (

tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_no_duplicate_users_in_shadow
  /home/james/envs/cloud-init/lib/python3.5/site-packages/simplestreams/mirrors/__init__.py:207: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self.prefix, path)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
==================================================================================== 18 passed, 2 warnings in 1195.55s (0:19:55) ====================================================================================
