correctly tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_random_passwords_emitted_to_serial_console
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.5.10, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, configfile: tox.ini
plugins: cov-2.11.1
collected 3 items

tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_random_passwords_emitted_to_serial_console Detected image: image_id=focal os=ubuntu release=focal

-------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------
2021-09-10 21:57:38 INFO      integration_testing:clouds.py:88 Detected image: image_id=focal os=ubuntu release=focal
2021-09-10 21:57:38 INFO      botocore.credentials:credentials.py:1217 Found credentials in shared credentials file: ~/.aws/credentials
Detected image: image_id=focal os=ubuntu release=focal
2021-09-10 21:57:38 INFO      integration_testing:clouds.py:88 Detected image: image_id=focal os=ubuntu release=focal
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=focal
PLATFORM=ec2
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-09-10 21:57:44 INFO      integration_testing:clouds.py:129 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=focal
PLATFORM=ec2
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for ec2
2021-09-10 21:57:44 INFO      integration_testing:conftest.py:156 Setting up environment for ec2
Launching instance with launch_kwargs:
image_id=ami-0a5a9780e8617afe7
user_data=None
2021-09-10 21:57:44 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=ami-0a5a9780e8617afe7
user_data=None
2021-09-10 21:58:31 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 21:58:31 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-09-10 21:58:31 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-10 21:58:34 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f507e3f2550>, instance=ec2.Instance(id='i-06ff29092c2eb0c29'))
2021-09-10 21:58:39 INFO      integration_testing:clouds.py:173 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f507e3f2550>, instance=ec2.Instance(id='i-06ff29092c2eb0c29'))
2021-09-10 21:58:39 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~20.04.1
2021-09-10 21:58:40 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~20.04.1
2021-09-10 21:58:40 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210907
2021-09-10 21:58:40 INFO      integration_testing:clouds.py:183 image serial: 20210907
Installing proposed image
2021-09-10 21:58:40 INFO      integration_testing:instances.py:150 Installing proposed image
2021-09-10 21:58:40 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-09-10 21:58:40 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-09-10 21:58:51 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-09-10 21:58:58 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~20.04.2
2021-09-10 21:58:59 INFO      integration_testing:instances.py:137 Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~20.04.2
2021-09-10 21:58:59 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-10 21:58:59 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-09-10 21:58:59 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-10 21:59:00 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-09-10 22:01:48 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 22:01:49 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 22:01:50 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-09-10 22:01:50 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-10 22:01:53 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Created new image: ami-0e325e0e90251ef87
2021-09-10 22:01:57 INFO      integration_testing:instances.py:114 Created new image: ami-0e325e0e90251ef87
Done with environment setup
2021-09-10 22:02:28 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=ami-0e325e0e90251ef87
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
  list:
    - tom:mypassword123!
    - dick:RANDOM
    - harry:RANDOM
    - mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-10 22:02:28 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=ami-0e325e0e90251ef87
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
  list:
    - tom:mypassword123!
    - dick:RANDOM
    - harry:RANDOM
    - mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-10 22:02:59 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 22:03:15 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-09-10 22:03:15 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-10 22:03:18 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f507e3f2550>, instance=ec2.Instance(id='i-0ea52fe8d9d33f465'))
2021-09-10 22:03:23 INFO      integration_testing:clouds.py:173 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f507e3f2550>, instance=ec2.Instance(id='i-0ea52fe8d9d33f465'))
2021-09-10 22:03:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.2
2021-09-10 22:03:23 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.2
2021-09-10 22:03:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210907
2021-09-10 22:03:24 INFO      integration_testing:clouds.py:183 image serial: 20210907
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_explicit_password_set_correctly Detected image: image_id=focal os=ubuntu release=focal

-------------------------------------------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------------------------------------------
2021-09-10 22:20:06 INFO      integration_testing:clouds.py:88 Detected image: image_id=focal os=ubuntu release=focal
-------------------------------------------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------------------------------------------
2021-09-10 22:20:06 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_random_passwords_emitted_to_serial_console Detected image: image_id=focal os=ubuntu release=focal

-------------------------------------------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------------------------------------------
2021-09-10 22:20:52 INFO      integration_testing:clouds.py:88 Detected image: image_id=focal os=ubuntu release=focal
Launching instance with launch_kwargs:
image_id=ami-0e325e0e90251ef87
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
    list: |
      tom:mypassword123!
      dick:RANDOM
      harry:RANDOM
      mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-10 22:20:52 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=ami-0e325e0e90251ef87
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
    list: |
      tom:mypassword123!
      dick:RANDOM
      harry:RANDOM
      mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-09-10 22:21:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 22:21:24 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-10 22:21:25 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-09-10 22:21:25 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-10 22:21:27 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f507e3f2550>, instance=ec2.Instance(id='i-0ebef15149835aeed'))
2021-09-10 22:21:32 INFO      integration_testing:clouds.py:173 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f507e3f2550>, instance=ec2.Instance(id='i-0ebef15149835aeed'))
2021-09-10 22:21:32 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.2
2021-09-10 22:21:32 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.2
2021-09-10 22:21:32 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210907
2021-09-10 22:21:33 INFO      integration_testing:clouds.py:183 image serial: 20210907
PASSEDDeleting snapshot image created for this testrun: ami-0e325e0e90251ef87

------------------------------------------------------------------------------------------------------------------------------------ live log teardown -------------------------------------------------------------------------------------------------------------------------------------
2021-09-10 22:38:44 INFO      integration_testing:clouds.py:204 Deleting snapshot image created for this testrun: ami-0e325e0e90251ef87


===================================================================================================================================== warnings summary =====================================================================================================================================
../envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8
  /home/james/envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
    from cryptography.hazmat.primitives.asymmetric.utils import (

tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_random_passwords_emitted_to_serial_console
  /home/james/envs/cloud-init/lib/python3.5/site-packages/simplestreams/mirrors/__init__.py:207: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self.prefix, path)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================================================================== 3 passed, 2 warnings in 2466.69s (0:41:06) ========================================================================================================================
