================================================ test session starts ================================================
platform linux -- Python 3.5.10, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, configfile: tox.ini
plugins: cov-2.11.1
collected 13 items

tests/integration_tests/modules/test_keys_to_console.py::TestKeysToConsoleBlacklist::test_excluded_keys[DSA] Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:04:06 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
2021-09-06 20:04:08 WARNING   google.auth._default:_default.py:352 No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
Detected image: image_id=hirsute os=ubuntu release=hirsute
2021-09-06 20:04:08 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=True
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=hirsute
PLATFORM=gce
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-09-06 20:04:13 INFO      integration_testing:clouds.py:129 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=True
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=hirsute
PLATFORM=gce
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for gce
2021-09-06 20:04:13 INFO      integration_testing:conftest.py:156 Setting up environment for gce
Launching instance with launch_kwargs:
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2104-hirsute-v20210831
user_data=None
2021-09-06 20:04:13 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2104-hirsute-v20210831
user_data=None
2021-09-06 20:04:16 WARNING   google.auth._default:_default.py:352 No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
2021-09-06 20:04:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:40 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:41 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:42 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:43 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:44 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:45 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:46 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:47 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:48 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:49 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:51 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:04:51 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-09-06 20:04:51 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-06 20:04:54 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=8675940911590132433)
2021-09-06 20:05:00 INFO      integration_testing:clouds.py:173 Launched instance: GceInstance(instance_id=8675940911590132433)
2021-09-06 20:05:00 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~21.04.1
2021-09-06 20:05:00 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~21.04.1
2021-09-06 20:05:00 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210831
2021-09-06 20:05:00 INFO      integration_testing:clouds.py:183 image serial: 20210831
Installing proposed image
2021-09-06 20:05:00 INFO      integration_testing:instances.py:150 Installing proposed image
2021-09-06 20:05:00 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-09-06 20:05:01 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-09-06 20:05:10 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-09-06 20:05:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-06 20:05:18 INFO      integration_testing:instances.py:137 Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-06 20:05:18 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-06 20:05:18 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image
2021-09-06 20:06:08 INFO      integration_testing:instances.py:114 Created new image: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image
Done with environment setup
2021-09-06 20:06:09 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image
user_data=#cloud-config
ssh_fp_console_blacklist: [ssh-dss, ssh-dsa, ecdsa-sha2-nistp256]
ssh_key_console_blacklist: [ssh-dss, ssh-dsa, ecdsa-sha2-nistp256]

2021-09-06 20:06:09 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image
user_data=#cloud-config
ssh_fp_console_blacklist: [ssh-dss, ssh-dsa, ecdsa-sha2-nistp256]
ssh_key_console_blacklist: [ssh-dss, ssh-dsa, ecdsa-sha2-nistp256]

2021-09-06 20:06:12 WARNING   google.auth._default:_default.py:352 No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
2021-09-06 20:06:21 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:06:37 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:06:38 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:06:39 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:06:39 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-09-06 20:06:40 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-06 20:06:46 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=5343593507382348381)
2021-09-06 20:06:53 INFO      integration_testing:clouds.py:173 Launched instance: GceInstance(instance_id=5343593507382348381)
2021-09-06 20:06:53 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-06 20:06:54 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-06 20:06:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210831
2021-09-06 20:06:54 INFO      integration_testing:clouds.py:183 image serial: 20210831
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:06:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_keys_to_console.py::TestKeysToConsoleBlacklist::test_excluded_keys[ECDSA] Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:06:54 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:06:55 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_keys_to_console.py::TestKeysToConsoleBlacklist::test_included_keys[ED25519] Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:06:55 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:06:55 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_keys_to_console.py::TestKeysToConsoleBlacklist::test_included_keys[RSA] Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:06:55 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:06:55 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_keys_to_console.py::TestAllKeysToConsoleBlacklist::test_header_excluded Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:06:55 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image
user_data=#cloud-config
ssh_fp_console_blacklist: [ssh-dsa, ssh-ecdsa, ssh-ed25519, ssh-rsa, ssh-dss, ecdsa-sha2-nistp256]

2021-09-06 20:06:55 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image
user_data=#cloud-config
ssh_fp_console_blacklist: [ssh-dsa, ssh-ecdsa, ssh-ed25519, ssh-rsa, ssh-dss, ecdsa-sha2-nistp256]

2021-09-06 20:07:00 WARNING   google.auth._default:_default.py:352 No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
2021-09-06 20:07:06 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:07:37 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-09-06 20:07:38 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-06 20:07:40 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=3671001215025269263)
2021-09-06 20:07:40 INFO      integration_testing:clouds.py:173 Launched instance: GceInstance(instance_id=3671001215025269263)
2021-09-06 20:07:40 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-06 20:07:41 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-06 20:07:41 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210831
2021-09-06 20:07:41 INFO      integration_testing:clouds.py:183 image serial: 20210831
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:07:41 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_keys_to_console.py::TestAllKeysToConsoleBlacklist::test_footer_excluded Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:07:42 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:07:42 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_keys_to_console.py::TestKeysToConsoleDisabled::test_keys_excluded[DSA] Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:07:42 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image
user_data=#cloud-config
ssh:
  emit_keys_to_console: false

2021-09-06 20:07:42 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image
user_data=#cloud-config
ssh:
  emit_keys_to_console: false

2021-09-06 20:07:45 WARNING   google.auth._default:_default.py:352 No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
2021-09-06 20:07:52 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:08:09 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:08:10 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:08:11 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:08:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:08:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:08:13 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-09-06 20:08:14 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-06 20:08:19 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=3769271724615125985)
2021-09-06 20:08:25 INFO      integration_testing:clouds.py:173 Launched instance: GceInstance(instance_id=3769271724615125985)
2021-09-06 20:08:25 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-06 20:08:25 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-06 20:08:25 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210831
2021-09-06 20:08:26 INFO      integration_testing:clouds.py:183 image serial: 20210831
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:08:26 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_keys_to_console.py::TestKeysToConsoleDisabled::test_keys_excluded[ECDSA] Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:08:26 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:08:26 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_keys_to_console.py::TestKeysToConsoleDisabled::test_keys_excluded[ED25519] Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:08:26 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:08:26 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_keys_to_console.py::TestKeysToConsoleDisabled::test_keys_excluded[RSA] Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:08:27 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:08:27 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_keys_to_console.py::TestKeysToConsoleDisabled::test_header_excluded Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:08:27 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:08:27 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_keys_to_console.py::TestKeysToConsoleDisabled::test_footer_excluded Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:08:27 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:08:27 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSED
tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py::TestSshAuthkeyFingerprints::test_ssh_authkey_fingerprints_enable Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------------------------- live log setup ---------------------------------------------------
2021-09-06 20:08:27 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image
user_data=#cloud-config
ssh_genkeytypes:
  - ecdsa
  - ed25519
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXW9Gg5H7ehjdSc6qDzwNtgCy94XYHhEYlXZMO2+FJrH3wfHGiMfCwOHxcOMt2QiXItULthdeQWS9QjBSSjVRXf6731igFrqPFyS9qBlOQ5D29C4HBXFnQggGVpBNJ82IRJv7szbbe/vpgLBP4kttUza9Dr4e1YM1ln4PRnjfXea6T0m+m1ixNb5432pTXlqYOnNOxSIm1gHgMLxPuDrJvQERDKrSiKSjIdyC9Jd8t2e1tkNLY0stmckVRbhShmcJvlyofHWbc2Ca1mmtP7MlS1VQnfLkvU1IrFwkmaQmaggX6WR6coRJ6XFXdWcq/AI2K6GjSnl1dnnCxE8VCEXBlXgFzad+PMSG4yiL5j8Oo1ZVpkTdgBnw4okGqTYCXyZg6X00As9IBNQfZMFlQXlIo4FiWgj3CO5QHQOyOX6FuEumaU13GnERrSSdp9tCs1Qm3/DG2RSCQBWTfcgMcStIvKqvJ3IjFn0vGLvI3Ampnq9q1SHwmmzAPSdzcMA76HyMUA5VWaBvWHlUxzIM6unxZASnwvuCzpywSEB5J2OF+p6H+cStJwQ32XwmOG8pLp1srlVWpqZI58Du/lzrkPqONphoZx0LDV86w7RUz1ksDzAdcm0tvmNRFMN1a0frDs506oA3aWK0oDk4Nmvk8sXGTYYw3iQSkOvDUUlIsqdaO+w==

2021-09-06 20:08:27 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image
user_data=#cloud-config
ssh_genkeytypes:
  - ecdsa
  - ed25519
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXW9Gg5H7ehjdSc6qDzwNtgCy94XYHhEYlXZMO2+FJrH3wfHGiMfCwOHxcOMt2QiXItULthdeQWS9QjBSSjVRXf6731igFrqPFyS9qBlOQ5D29C4HBXFnQggGVpBNJ82IRJv7szbbe/vpgLBP4kttUza9Dr4e1YM1ln4PRnjfXea6T0m+m1ixNb5432pTXlqYOnNOxSIm1gHgMLxPuDrJvQERDKrSiKSjIdyC9Jd8t2e1tkNLY0stmckVRbhShmcJvlyofHWbc2Ca1mmtP7MlS1VQnfLkvU1IrFwkmaQmaggX6WR6coRJ6XFXdWcq/AI2K6GjSnl1dnnCxE8VCEXBlXgFzad+PMSG4yiL5j8Oo1ZVpkTdgBnw4okGqTYCXyZg6X00As9IBNQfZMFlQXlIo4FiWgj3CO5QHQOyOX6FuEumaU13GnERrSSdp9tCs1Qm3/DG2RSCQBWTfcgMcStIvKqvJ3IjFn0vGLvI3Ampnq9q1SHwmmzAPSdzcMA76HyMUA5VWaBvWHlUxzIM6unxZASnwvuCzpywSEB5J2OF+p6H+cStJwQ32XwmOG8pLp1srlVWpqZI58Du/lzrkPqONphoZx0LDV86w7RUz1ksDzAdcm0tvmNRFMN1a0frDs506oA3aWK0oDk4Nmvk8sXGTYYw3iQSkOvDUUlIsqdaO+w==

2021-09-06 20:08:30 WARNING   google.auth._default:_default.py:352 No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
2021-09-06 20:08:38 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:08:55 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:08:56 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:08:57 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:08:58 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 20:08:58 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-09-06 20:08:59 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-06 20:09:04 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=6247808728781540307)
2021-09-06 20:09:13 INFO      integration_testing:clouds.py:173 Launched instance: GceInstance(instance_id=6247808728781540307)
2021-09-06 20:09:13 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-06 20:09:13 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.2
2021-09-06 20:09:13 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210831
2021-09-06 20:09:13 INFO      integration_testing:clouds.py:183 image serial: 20210831
--------------------------------------------------- live log call ---------------------------------------------------
2021-09-06 20:09:13 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSEDDeleting snapshot image created for this testrun: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image

------------------------------------------------- live log teardown -------------------------------------------------
2021-09-06 20:09:14 INFO      integration_testing:clouds.py:204 Deleting snapshot image created for this testrun: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-0906-150406-image


================================================= warnings summary ==================================================
../envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8
  /home/james/envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
    from cryptography.hazmat.primitives.asymmetric.utils import (

tests/integration_tests/modules/test_keys_to_console.py::TestKeysToConsoleBlacklist::test_excluded_keys[DSA]
  /home/james/envs/cloud-init/lib/python3.5/site-packages/simplestreams/mirrors/__init__.py:207: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self.prefix, path)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
==================================== 13 passed, 2 warnings in 309.20s (0:05:09) =====================================
