========================================== test session starts ===========================================
platform linux -- Python 3.5.10, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, configfile: tox.ini
plugins: cov-2.11.1
collected 2 items

tests/integration_tests/test_upgrade.py::test_subsequent_boot_of_upgraded_package Detected image: image_id=focal os=ubuntu release=focal

--------------------------------------------- live log setup ---------------------------------------------
2021-09-06 19:38:13 INFO      integration_testing:clouds.py:88 Detected image: image_id=focal os=ubuntu release=focal
2021-09-06 19:38:15 WARNING   google.auth._default:_default.py:352 No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
Detected image: image_id=focal os=ubuntu release=focal
2021-09-06 19:38:15 INFO      integration_testing:clouds.py:88 Detected image: image_id=focal os=ubuntu release=focal
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=focal
PLATFORM=gce
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-09-06 19:38:20 INFO      integration_testing:clouds.py:129 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=focal
PLATFORM=gce
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Launching instance with launch_kwargs:
user_data=None
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2004-focal-v20210831
--------------------------------------------- live log call ----------------------------------------------
2021-09-06 19:38:20 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
user_data=None
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2004-focal-v20210831
2021-09-06 19:38:23 WARNING   google.auth._default:_default.py:352 No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
2021-09-06 19:38:32 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:48 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:49 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:50 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:51 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:52 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:53 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:55 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:56 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:57 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:58 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:59 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:38:59 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-09-06 19:39:00 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-06 19:39:03 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=3229523515239289026)
2021-09-06 19:39:07 INFO      integration_testing:clouds.py:173 Launched instance: GceInstance(instance_id=3229523515239289026)
2021-09-06 19:39:07 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~20.04.1
2021-09-06 19:39:08 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~20.04.1
2021-09-06 19:39:08 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210831
2021-09-06 19:39:08 INFO      integration_testing:clouds.py:183 image serial: 20210831
Installing proposed image
2021-09-06 19:39:08 INFO      integration_testing:instances.py:150 Installing proposed image
2021-09-06 19:39:08 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-09-06 19:39:08 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-09-06 19:39:18 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-09-06 19:39:26 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~20.04.2
2021-09-06 19:39:27 INFO      integration_testing:instances.py:137 Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~20.04.2
Restarting instance and waiting for boot
2021-09-06 19:39:27 INFO      integration_testing:instances.py:66 Restarting instance and waiting for boot
2021-09-06 19:39:55 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:40:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:40:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:40:13 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-09-06 19:40:15 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-06 19:40:17 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
2021-09-06 19:40:18 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init status --wait --long'
PASSED
tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py::TestSshAuthkeyFingerprints::test_ssh_authkey_fingerprints_enable Detected image: image_id=focal os=ubuntu release=focal

--------------------------------------------- live log setup ---------------------------------------------
2021-09-06 19:41:05 INFO      integration_testing:clouds.py:88 Detected image: image_id=focal os=ubuntu release=focal
Setting up environment for gce
2021-09-06 19:41:05 INFO      integration_testing:conftest.py:156 Setting up environment for gce
Launching instance with launch_kwargs:
user_data=None
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2004-focal-v20210831
2021-09-06 19:41:05 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
user_data=None
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2004-focal-v20210831
2021-09-06 19:41:08 WARNING   google.auth._default:_default.py:352 No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
2021-09-06 19:41:16 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:33 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:34 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:35 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:36 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:37 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:38 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:39 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:40 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:41 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:42 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:43 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:45 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:41:45 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-09-06 19:41:45 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-06 19:41:50 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=1849808066453426237)
2021-09-06 19:41:54 INFO      integration_testing:clouds.py:173 Launched instance: GceInstance(instance_id=1849808066453426237)
2021-09-06 19:41:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~20.04.1
2021-09-06 19:41:54 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~20.04.1
2021-09-06 19:41:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210831
2021-09-06 19:41:54 INFO      integration_testing:clouds.py:183 image serial: 20210831
Installing proposed image
2021-09-06 19:41:54 INFO      integration_testing:instances.py:150 Installing proposed image
2021-09-06 19:41:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-09-06 19:41:55 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-09-06 19:42:05 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-09-06 19:42:14 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~20.04.2
2021-09-06 19:42:15 INFO      integration_testing:instances.py:137 Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~20.04.2
2021-09-06 19:42:15 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-06 19:42:16 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: projects/ubuntu-server-277015/global/images/i1-gce-integration-test-0906-143813-image
2021-09-06 19:43:12 INFO      integration_testing:instances.py:114 Created new image: projects/ubuntu-server-277015/global/images/i1-gce-integration-test-0906-143813-image
Done with environment setup
2021-09-06 19:43:13 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
user_data=#cloud-config
ssh_genkeytypes:
  - ecdsa
  - ed25519
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXW9Gg5H7ehjdSc6qDzwNtgCy94XYHhEYlXZMO2+FJrH3wfHGiMfCwOHxcOMt2QiXItULthdeQWS9QjBSSjVRXf6731igFrqPFyS9qBlOQ5D29C4HBXFnQggGVpBNJ82IRJv7szbbe/vpgLBP4kttUza9Dr4e1YM1ln4PRnjfXea6T0m+m1ixNb5432pTXlqYOnNOxSIm1gHgMLxPuDrJvQERDKrSiKSjIdyC9Jd8t2e1tkNLY0stmckVRbhShmcJvlyofHWbc2Ca1mmtP7MlS1VQnfLkvU1IrFwkmaQmaggX6WR6coRJ6XFXdWcq/AI2K6GjSnl1dnnCxE8VCEXBlXgFzad+PMSG4yiL5j8Oo1ZVpkTdgBnw4okGqTYCXyZg6X00As9IBNQfZMFlQXlIo4FiWgj3CO5QHQOyOX6FuEumaU13GnERrSSdp9tCs1Qm3/DG2RSCQBWTfcgMcStIvKqvJ3IjFn0vGLvI3Ampnq9q1SHwmmzAPSdzcMA76HyMUA5VWaBvWHlUxzIM6unxZASnwvuCzpywSEB5J2OF+p6H+cStJwQ32XwmOG8pLp1srlVWpqZI58Du/lzrkPqONphoZx0LDV86w7RUz1ksDzAdcm0tvmNRFMN1a0frDs506oA3aWK0oDk4Nmvk8sXGTYYw3iQSkOvDUUlIsqdaO+w==

image_id=projects/ubuntu-server-277015/global/images/i1-gce-integration-test-0906-143813-image
2021-09-06 19:43:13 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
user_data=#cloud-config
ssh_genkeytypes:
  - ecdsa
  - ed25519
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXW9Gg5H7ehjdSc6qDzwNtgCy94XYHhEYlXZMO2+FJrH3wfHGiMfCwOHxcOMt2QiXItULthdeQWS9QjBSSjVRXf6731igFrqPFyS9qBlOQ5D29C4HBXFnQggGVpBNJ82IRJv7szbbe/vpgLBP4kttUza9Dr4e1YM1ln4PRnjfXea6T0m+m1ixNb5432pTXlqYOnNOxSIm1gHgMLxPuDrJvQERDKrSiKSjIdyC9Jd8t2e1tkNLY0stmckVRbhShmcJvlyofHWbc2Ca1mmtP7MlS1VQnfLkvU1IrFwkmaQmaggX6WR6coRJ6XFXdWcq/AI2K6GjSnl1dnnCxE8VCEXBlXgFzad+PMSG4yiL5j8Oo1ZVpkTdgBnw4okGqTYCXyZg6X00As9IBNQfZMFlQXlIo4FiWgj3CO5QHQOyOX6FuEumaU13GnERrSSdp9tCs1Qm3/DG2RSCQBWTfcgMcStIvKqvJ3IjFn0vGLvI3Ampnq9q1SHwmmzAPSdzcMA76HyMUA5VWaBvWHlUxzIM6unxZASnwvuCzpywSEB5J2OF+p6H+cStJwQ32XwmOG8pLp1srlVWpqZI58Du/lzrkPqONphoZx0LDV86w7RUz1ksDzAdcm0tvmNRFMN1a0frDs506oA3aWK0oDk4Nmvk8sXGTYYw3iQSkOvDUUlIsqdaO+w==

image_id=projects/ubuntu-server-277015/global/images/i1-gce-integration-test-0906-143813-image
2021-09-06 19:43:16 WARNING   google.auth._default:_default.py:352 No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
2021-09-06 19:43:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:43:39 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:43:40 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:43:41 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-06 19:43:41 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-09-06 19:43:42 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-06 19:43:46 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=6243051884997497278)
2021-09-06 19:43:55 INFO      integration_testing:clouds.py:173 Launched instance: GceInstance(instance_id=6243051884997497278)
2021-09-06 19:43:55 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.2
2021-09-06 19:43:55 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.2
2021-09-06 19:43:55 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210831
2021-09-06 19:43:56 INFO      integration_testing:clouds.py:183 image serial: 20210831
--------------------------------------------- live log call ----------------------------------------------
2021-09-06 19:43:56 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSEDDeleting snapshot image created for this testrun: projects/ubuntu-server-277015/global/images/i1-gce-integration-test-0906-143813-image

------------------------------------------- live log teardown --------------------------------------------
2021-09-06 19:44:14 INFO      integration_testing:clouds.py:204 Deleting snapshot image created for this testrun: projects/ubuntu-server-277015/global/images/i1-gce-integration-test-0906-143813-image


============================================ warnings summary ============================================
../envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8
  /home/james/envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
    from cryptography.hazmat.primitives.asymmetric.utils import (

tests/integration_tests/test_upgrade.py::test_subsequent_boot_of_upgraded_package
  /home/james/envs/cloud-init/lib/python3.5/site-packages/simplestreams/mirrors/__init__.py:207: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self.prefix, path)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================== 2 passed, 2 warnings in 362.03s (0:06:02) ================================
