Upstream test at:
https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/test_upgrade.py

Logs from individual before/after runs in azure-sru-21.2-3 subdirectory

==== Bionic ====
-------------------------------- live log setup --------------------------------
2021-05-17 22:20:58 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-05-17 22:20:58 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
Launching instance with launch_kwargs:
image_id=Canonical:UbuntuServer:18.04-DAILY-LTS
user_data=#cloud-config
hostname: SRU-worked

2021-05-17 22:20:58 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=Canonical:UbuntuServer:18.04-DAILY-LTS
user_data=#cloud-config
hostname: SRU-worked

2021-05-17 22:21:45 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-05-17 22:21:45 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-05-17 22:21:45 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-05-17 22:21:47 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7eff470f5f98>
2021-05-17 22:21:48 INFO      integration_testing:clouds.py:173 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7eff470f5f98>
2021-05-17 22:21:48 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~18.04.2
2021-05-17 22:21:48 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~18.04.2
2021-05-17 22:21:48 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210514
2021-05-17 22:21:48 INFO      integration_testing:clouds.py:183 image serial: 20210514
2021-05-17 22:21:48 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c hostname
2021-05-17 22:21:49 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'dpkg-query --show cloud-init'
2021-05-17 22:21:49 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /run/cloud-init/result.json'
2021-05-17 22:21:49 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init init'
2021-05-17 22:21:50 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep Trace /var/log/cloud-init.log'
2021-05-17 22:21:50 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c cloud-id
2021-05-17 22:21:50 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-05-17 22:21:50 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c systemd-analyze
2021-05-17 22:21:51 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'systemd-analyze blame'
2021-05-17 22:21:51 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze show'
2021-05-17 22:21:51 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze blame'
Installing proposed image
2021-05-17 22:21:52 INFO      integration_testing:instances.py:144 Installing proposed image
2021-05-17 22:21:52 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-05-17 22:22:12 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.2-3-g899bfaa9-0ubuntu2~18.04.1
2021-05-17 22:22:12 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.2-3-g899bfaa9-0ubuntu2~18.04.1
2021-05-17 22:22:12 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-05-17 22:22:13 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-05-17 22:22:13 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'hostname something-else'
Restarting instance and waiting for boot
2021-05-17 22:22:13 INFO      integration_testing:instances.py:65 Restarting instance and waiting for boot
2021-05-17 22:22:43 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-05-17 22:22:59 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 20.84.225.1
Retrying SSH connection to ubuntu@20.84.225.1:22 (584s left)
2021-05-17 22:23:00 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 20.84.225.1
Retrying SSH connection to ubuntu@20.84.225.1:22 (583s left)
2021-05-17 22:23:01 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-05-17 22:23:01 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-05-17 22:23:02 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
2021-05-17 22:23:06 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init status --wait --long'
2021-05-17 22:23:06 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init status --wait --long'
2021-05-17 22:23:07 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c hostname
2021-05-17 22:23:07 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'dpkg-query --show cloud-init'
2021-05-17 22:23:07 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /run/cloud-init/result.json'
2021-05-17 22:23:07 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init init'
2021-05-17 22:23:08 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep Trace /var/log/cloud-init.log'
2021-05-17 22:23:08 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c cloud-id
2021-05-17 22:23:08 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-05-17 22:23:08 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c systemd-analyze
2021-05-17 22:23:08 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'systemd-analyze blame'
2021-05-17 22:23:09 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze show'
2021-05-17 22:23:09 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze blame'
Wrote upgrade test logs to /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_bionic_before_210517171429.log and /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_bionic_after_210517171429.log
2021-05-17 22:23:50 INFO      integration_testing:test_upgrade.py:102 Wrote upgrade test logs to /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_bionic_before_210517171429.log and /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_bionic_after_210517171429.log
PASSED


==== Focal ====
-------------------------------- live log setup --------------------------------
2021-05-18 06:30:21 INFO      integration_testing:clouds.py:88 Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
-------------------------------- live log call ---------------------------------
2021-05-18 06:30:21 INFO      integration_testing:clouds.py:88 Detected image: image_id=focal os=ubuntu release=focal
Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-focal-daily:20_04-daily-lts
user_data=#cloud-config
hostname: SRU-worked

2021-05-18 06:30:21 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-focal-daily:20_04-daily-lts
user_data=#cloud-config
hostname: SRU-worked

2021-05-18 06:31:38 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-05-18 06:31:38 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-05-18 06:31:39 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-05-18 06:31:42 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f78d374e668>
2021-05-18 06:31:43 INFO      integration_testing:clouds.py:173 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f78d374e668>
2021-05-18 06:31:43 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.04.2
2021-05-18 06:31:43 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.04.2
2021-05-18 06:31:43 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210513.1
2021-05-18 06:31:43 INFO      integration_testing:clouds.py:183 image serial: 20210513.1
2021-05-18 06:31:43 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c hostname
2021-05-18 06:31:44 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'dpkg-query --show cloud-init'
2021-05-18 06:31:44 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /run/cloud-init/result.json'
2021-05-18 06:31:44 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init init'
2021-05-18 06:31:45 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep Trace /var/log/cloud-init.log'
2021-05-18 06:31:45 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c cloud-id
2021-05-18 06:31:46 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-05-18 06:31:46 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c systemd-analyze
2021-05-18 06:31:46 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'systemd-analyze blame'
2021-05-18 06:31:47 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze show'
2021-05-18 06:31:47 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze blame'
Installing proposed image
2021-05-18 06:31:48 INFO      integration_testing:instances.py:144 Installing proposed image
2021-05-18 06:31:48 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-05-18 06:32:16 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.2-3-g899bfaa9-0ubuntu2~20.04.1
2021-05-18 06:32:17 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.2-3-g899bfaa9-0ubuntu2~20.04.1
2021-05-18 06:32:17 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-05-18 06:32:17 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-05-18 06:32:17 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'hostname something-else'
Restarting instance and waiting for boot
2021-05-18 06:32:17 INFO      integration_testing:instances.py:65 Restarting instance and waiting for boot
2021-05-18 06:32:48 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-05-18 06:33:19 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-05-18 06:33:20 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-05-18 06:33:21 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
2021-05-18 06:33:23 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init status --wait --long'
2021-05-18 06:33:24 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init status --wait --long'
2021-05-18 06:33:24 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c hostname
2021-05-18 06:33:24 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'dpkg-query --show cloud-init'
2021-05-18 06:33:25 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /run/cloud-init/result.json'
2021-05-18 06:33:25 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init init'
2021-05-18 06:33:27 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep Trace /var/log/cloud-init.log'
2021-05-18 06:33:27 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c cloud-id
2021-05-18 06:33:27 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-05-18 06:33:27 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c systemd-analyze
2021-05-18 06:33:28 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'systemd-analyze blame'
2021-05-18 06:33:28 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze show'
2021-05-18 06:33:29 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze blame'
Wrote upgrade test logs to /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_focal_before_210518012310.log and /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_focal_after_210518012310.log
2021-05-18 06:34:10 INFO      integration_testing:test_upgrade.py:102 Wrote upgrade test logs to /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_focal_before_210518012310.log and /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_focal_after_210518012310.log
PASSED


==== Groovy ====
-------------------------------- live log setup --------------------------------
2021-05-19 03:05:20 INFO      integration_testing:clouds.py:88 Detected image: image_id=groovy os=ubuntu release=groovy
Detected image: image_id=groovy os=ubuntu release=groovy
-------------------------------- live log call ---------------------------------
2021-05-19 03:05:20 INFO      integration_testing:clouds.py:88 Detected image: image_id=groovy os=ubuntu release=groovy
Launching instance with launch_kwargs:
user_data=#cloud-config
hostname: SRU-worked

image_id=Canonical:0001-com-ubuntu-server-groovy-daily:20_10-daily
2021-05-19 03:05:20 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
user_data=#cloud-config
hostname: SRU-worked

image_id=Canonical:0001-com-ubuntu-server-groovy-daily:20_10-daily
2021-05-19 03:06:08 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-05-19 03:06:08 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.3p1)
2021-05-19 03:06:08 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-05-19 03:06:11 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f176aaa59e8>
2021-05-19 03:06:12 INFO      integration_testing:clouds.py:173 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f176aaa59e8>
2021-05-19 03:06:12 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.10.2
2021-05-19 03:06:12 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.10.2
2021-05-19 03:06:12 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210514
2021-05-19 03:06:12 INFO      integration_testing:clouds.py:183 image serial: 20210514
2021-05-19 03:06:12 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c hostname
2021-05-19 03:06:12 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'dpkg-query --show cloud-init'
2021-05-19 03:06:13 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /run/cloud-init/result.json'
2021-05-19 03:06:13 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init init'
2021-05-19 03:06:14 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep Trace /var/log/cloud-init.log'
2021-05-19 03:06:14 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c cloud-id
2021-05-19 03:06:15 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-05-19 03:06:15 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c systemd-analyze
2021-05-19 03:06:15 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'systemd-analyze blame'
2021-05-19 03:06:16 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze show'
2021-05-19 03:06:16 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze blame'
Installing proposed image
2021-05-19 03:06:17 INFO      integration_testing:instances.py:144 Installing proposed image
2021-05-19 03:06:17 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-05-19 03:06:40 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.2-3-g899bfaa9-0ubuntu2~20.10.1
2021-05-19 03:06:41 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.2-3-g899bfaa9-0ubuntu2~20.10.1
2021-05-19 03:06:41 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-05-19 03:06:41 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-05-19 03:06:41 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'hostname something-else'
Restarting instance and waiting for boot
2021-05-19 03:06:42 INFO      integration_testing:instances.py:65 Restarting instance and waiting for boot
2021-05-19 03:07:12 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-05-19 03:07:28 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 20.40.247.109
Retrying SSH connection to ubuntu@20.40.247.109:22 (584s left)
2021-05-19 03:07:29 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 20.40.247.109
Retrying SSH connection to ubuntu@20.40.247.109:22 (583s left)
2021-05-19 03:07:30 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 20.40.247.109
Retrying SSH connection to ubuntu@20.40.247.109:22 (582s left)
2021-05-19 03:07:31 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 20.40.247.109
Retrying SSH connection to ubuntu@20.40.247.109:22 (581s left)
2021-05-19 03:07:32 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 20.40.247.109
Retrying SSH connection to ubuntu@20.40.247.109:22 (580s left)
2021-05-19 03:07:33 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.3p1)
2021-05-19 03:07:33 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-05-19 03:07:35 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
2021-05-19 03:07:40 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init status --wait --long'
2021-05-19 03:07:40 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init status --wait --long'
2021-05-19 03:07:41 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c hostname
2021-05-19 03:07:41 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'dpkg-query --show cloud-init'
2021-05-19 03:07:41 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /run/cloud-init/result.json'
2021-05-19 03:07:41 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init init'
2021-05-19 03:07:43 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep Trace /var/log/cloud-init.log'
2021-05-19 03:07:43 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c cloud-id
2021-05-19 03:07:43 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-05-19 03:07:43 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c systemd-analyze
2021-05-19 03:07:44 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'systemd-analyze blame'
2021-05-19 03:07:45 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze show'
2021-05-19 03:07:45 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze blame'
Wrote upgrade test logs to /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_groovy_before_210518215821.log and /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_groovy_after_210518215821.log
2021-05-19 03:08:26 INFO      integration_testing:test_upgrade.py:102 Wrote upgrade test logs to /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_groovy_before_210518215821.log and /home/james/tmp_home/cloud_init_test_logs/test_upgrade_azure_groovy_after_210518215821.log
PASSED


==== Hirsute ====
-------------------------------------------------------------- live log setup ---------------------------------------------------------------
2021-05-19 20:54:40 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
Detected image: image_id=hirsute os=ubuntu release=hirsute
2021-05-19 20:54:41 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ALWAYS
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=hirsute
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-05-19 20:54:41 INFO      integration_testing:clouds.py:129 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ALWAYS
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=hirsute
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Detected image: image_id=hirsute os=ubuntu release=hirsute
--------------------------------------------------------------- live log call ---------------------------------------------------------------
2021-05-19 20:54:41 INFO      integration_testing:clouds.py:88 Detected image: image_id=hirsute os=ubuntu release=hirsute
Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-hirsute-daily:21_04-daily
user_data=#cloud-config
hostname: SRU-worked

2021-05-19 20:54:41 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-hirsute-daily:21_04-daily
user_data=#cloud-config
hostname: SRU-worked

2021-05-19 20:56:13 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-05-19 20:56:13 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-05-19 20:56:13 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-05-19 20:56:14 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fe0ab813eb8>
2021-05-19 20:56:17 INFO      integration_testing:clouds.py:173 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fe0ab813eb8>
2021-05-19 20:56:17 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu2
2021-05-19 20:56:18 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu2
2021-05-19 20:56:18 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210323
2021-05-19 20:56:18 INFO      integration_testing:clouds.py:183 image serial: 20210323
2021-05-19 20:56:18 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c hostname
2021-05-19 20:56:18 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'dpkg-query --show cloud-init'
2021-05-19 20:56:18 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /run/cloud-init/result.json'
2021-05-19 20:56:18 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init init'
2021-05-19 20:56:19 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep Trace /var/log/cloud-init.log'
2021-05-19 20:56:19 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c cloud-id
2021-05-19 20:56:20 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-05-19 20:56:20 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c systemd-analyze
2021-05-19 20:56:20 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'systemd-analyze blame'
2021-05-19 20:56:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze show'
2021-05-19 20:56:21 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze blame'
Installing proposed image
2021-05-19 20:56:22 INFO      integration_testing:instances.py:144 Installing proposed image
2021-05-19 20:56:22 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-05-19 20:56:53 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.2-3-g899bfaa9-0ubuntu2~21.04.1
2021-05-19 20:56:54 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.2-3-g899bfaa9-0ubuntu2~21.04.1
2021-05-19 20:56:54 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-05-19 20:56:54 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-05-19 20:56:54 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'hostname something-else'
Restarting instance and waiting for boot
2021-05-19 20:56:54 INFO      integration_testing:instances.py:65 Restarting instance and waiting for boot
2021-05-19 20:57:25 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-05-19 20:57:40 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-05-19 20:57:40 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-05-19 20:57:41 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
2021-05-19 20:57:43 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init status --wait --long'
2021-05-19 20:57:44 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init status --wait --long'
2021-05-19 20:57:44 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c hostname
2021-05-19 20:57:44 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'dpkg-query --show cloud-init'
2021-05-19 20:57:44 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /run/cloud-init/result.json'
2021-05-19 20:57:44 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init init'
2021-05-19 20:57:46 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep Trace /var/log/cloud-init.log'
2021-05-19 20:57:46 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c cloud-id
2021-05-19 20:57:47 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-05-19 20:57:47 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c systemd-analyze
2021-05-19 20:57:47 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'systemd-analyze blame'
2021-05-19 20:57:48 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze show'
2021-05-19 20:57:48 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init analyze blame'
Wrote upgrade test logs to /tmp/cloud_init_test_logs/test_upgrade_azure_hirsute_before_210519155440.log and /tmp/cloud_init_test_logs/test_upgrade_azure_hirsute_after_210519155440.log
2021-05-19 20:58:29 INFO      integration_testing:test_upgrade.py:102 Wrote upgrade test logs to /tmp/cloud_init_test_logs/test_upgrade_azure_hirsute_before_210519155440.log and /tmp/cloud_init_test_logs/test_upgrade_azure_hirsute_after_210519155440.log
PASSED
